<?php
// Source: Psalm ConstValuesTest.php
// Hand-ported: the upstream cases are valid-code snippets with no
// assertions, so each assertType() states the type the snippet implies.
// Not generated by scripts/extract_psalm_tests.php.

// Test: enumStringOrEnumIntCorrect
namespace PsalmTest_const_values_1 {
    /** @psalm-param ( "foo" | "bar" | 1 | 2 | 3 ) $s */
    function foo($s) : void {
        assertType("'bar'|'foo'|1|2|3", $s);
    }
}

// Test: enumStringOrEnumIntWithoutSpacesCorrect
namespace PsalmTest_const_values_2 {
    /** @psalm-param "foo"|"bar"|1|2|3|4.0|4.1 $s */
    function foo($s) : void {
        assertType("'bar'|'foo'|1|2|3|4.0|4.1", $s);
    }
}

// Test: noRedundantConditionWithSwitch
namespace PsalmTest_const_values_3 {
    /**
     * @psalm-param ( "foo" | "bar") $s
     */
    function foo(string $s) : void {
        switch ($s) {
          case "foo":
            assertType("'foo'", $s);
            break;
          case "bar":
            assertType("'bar'", $s);
            break;
        }
    }
}

// Test: classConstantCorrect
namespace PsalmTest_const_values_4 {
    class C {
        const A1 = "bat";
        const B = "baz";
    }
    /** @psalm-param "foo"|"bar"|C::A1|C::B $s */
    function foo($s) : void {
        assertType("'bar'|'bat'|'baz'|'foo'", $s); // SKIP: a class constant named as a docblock type is not read
    }
}

// Test: selfClassConstGoodValue
namespace PsalmTest_const_values_5 {
    class A {
        const FOO = "foo";
        const BAR = "bar";

        /**
         * @param (self::FOO | self::BAR) $s
         */
        public static function foo(string $s) : void {
            assertType("'bar'|'foo'", $s); // SKIP: a class constant named as a docblock type is not read
        }
    }
}

// Test: classConstants
namespace PsalmTest_const_values_6 {
    use PsalmTest_const_values_6_other\C as E;
    class C {}
    class D {};
    /** @psalm-param C::class|D::class|E::class $s */
    function foo(string $s) : void {
        assertType("'PsalmTest_const_values_6\\\\C'|'PsalmTest_const_values_6\\\\D'|'PsalmTest_const_values_6_other\\\\C'", $s); // SKIP: a class constant named as a docblock type is not read
    }
}

namespace PsalmTest_const_values_6_other {
    class C {}
}
