<?php
// Source: Psalm KeyOfArrayTest.php
// Hand-ported: the upstream cases are valid-code snippets with no
// assertions, so each assertType() states the type the snippet implies.
// Not generated by scripts/extract_psalm_tests.php.

// Test: keyOfListClassConstant
namespace PsalmTest_key_of_array_1 {
    class A {
        const FOO = [
            "bar"
        ];
        /** @return key-of<A::FOO> */
        public function getKey() {
            return 0;
        }
    }

    assertType('0', (new A())->getKey());
}

// Test: keyOfAssociativeArrayClassConstant
namespace PsalmTest_key_of_array_2 {
    class A {
        const FOO = [
            "bar" => 42
        ];
        /** @return key-of<A::FOO> */
        public function getKey() {
            return "bar";
        }
    }

    assertType("'bar'", (new A())->getKey());
}

// Test: allKeysOfAssociativeArrayPossible
namespace PsalmTest_key_of_array_3 {
    class A {
        const FOO = [
            "bar" => 42,
            "adams" => 43,
        ];
        /** @return key-of<A::FOO> */
        public function getKey(bool $adams) {
            if ($adams) {
                return "adams";
            }
            return "bar";
        }
    }

    assertType("'adams'|'bar'", (new A())->getKey(true));
}

// Test: keyOfAsArray
namespace PsalmTest_key_of_array_4 {
    class A {
        /** @var array */
        const FOO = [
            "bar" => 42,
            "adams" => 43,
        ];
        /** @return key-of<self::FOO>[] */
        public function getKey() {
            return array_keys(self::FOO);
        }
    }

    assertType("array<'bar'|'adams'>", (new A())->getKey());
}

// Test: keyOfArrayLiteral
namespace PsalmTest_key_of_array_5 {
    /**
     * @return key-of<array<int, string>>
     */
    function getKey() {
        return 32;
    }

    assertType('int', getKey());
}

// Test: keyOfUnionArrayLiteral
namespace PsalmTest_key_of_array_6 {
    /**
     * @return key-of<array<int, string>|array<string, string>>
     */
    function getKey(bool $asString) {
        if ($asString) {
            return "42";
        }
        return 42;
    }

    assertType('int|string', getKey(true));
}

// Test: keyOfUnionListAndKeyedArray
namespace PsalmTest_key_of_array_7 {
    /**
     * @return key-of<list<int>|array{a: int, b: int}>
     */
    function getKey(bool $asInt) {
        if ($asInt) {
            return 42;
        }
        return "a";
    }

    assertType("'a'|'b'|int", getKey(true));
}

// Test: keyOfListArrayLiteral
namespace PsalmTest_key_of_array_8 {
    /**
     * @return key-of<list<string>>
     */
    function getKey() {
        return 42;
    }

    assertType('int', getKey());
}

// Test: keyOfStringArrayConformsToString
namespace PsalmTest_key_of_array_9 {
    /**
     * @return string
     */
    function getKey2() {
        /** @var key-of<array<string, string>>[] */
        $keys2 = ["foo"];
        assertType('string', $keys2[0]);
        return $keys2[0];
    }
}
