<?php
// Source: Psalm Template/ClassStringMapTest.php
// Hand-ported: the upstream cases are valid-code snippets with no
// assertions, so each assertType() states the type the snippet implies.
// Not generated by scripts/extract_psalm_tests.php.

// Test: basicClassStringMap
namespace PsalmTest_template_class_string_map_1 {
    /**
     * @psalm-consistent-constructor
     */
    class Foo {}

    class FooChild extends Foo {}

    class A {
        /** @var class-string-map<T as Foo, T> */
        public static array $map = [];

        /**
         * @template T as Foo
         * @param class-string<T> $class
         * @return T
         */
        public function get(string $class) : Foo {
            if (isset(self::$map[$class])) {
                return self::$map[$class];
            }

            self::$map[$class] = new $class();
            return self::$map[$class];
        }
    }

    assertType('Foo', (new A())->get(Foo::class));
    assertType('FooChild', (new A())->get(FooChild::class));
}

// Test: basicClassStringMapDifferentTemplateName
namespace PsalmTest_template_class_string_map_2 {
    /**
     * @psalm-consistent-constructor
     */
    class Foo {}

    class FooChild extends Foo {}

    class A {
        /** @var class-string-map<T as Foo, T> */
        public static array $map = [];

        /**
         * @template U as Foo
         * @param class-string<U> $class
         * @return U
         */
        public function get(string $class) : Foo {
            if (isset(self::$map[$class])) {
                return self::$map[$class];
            }

            self::$map[$class] = new $class();
            return self::$map[$class];
        }
    }

    assertType('Foo', (new A())->get(Foo::class));
    assertType('FooChild', (new A())->get(FooChild::class));
}

// Test: simpleSetter
// Upstream only stores into the map; a getter was added so the
// `class-string<U>` → `U` binding is observable.
namespace PsalmTest_template_class_string_map_3 {
    class Service {}

    class Container {
        /** @var class-string-map<T, T> */
        public array $map = [];

        /**
         * @template U of object
         * @param class-string<U> $key
         * @param U $obj
         */
        public function set(string $key, object $obj): void {
            $this->map[$key] = $obj;
        }

        /**
         * @template U of object
         * @param class-string<U> $key
         * @return U
         */
        public function get(string $key): object {
            return $this->map[$key];
        }
    }

    function test(Container $c): void {
        $c->set(Service::class, new Service());
        assertType('Service', $c->get(Service::class));
    }
}
