<?php
// Source: Psalm Template/NestedTemplateTest.php
// Hand-ported: the upstream cases are valid-code snippets with no
// assertions, so each assertType() states the type the snippet implies.
// Not generated by scripts/extract_psalm_tests.php.

// Test: nestedTemplateExtends
// Upstream's classes are empty; a getter per template parameter was added
// to BaseRepository so the bound arguments have something to observe.
namespace PsalmTest_template_nested_template_1 {
    interface IBaseViewData {}

    /**
     * @template TViewData
     */
    class BaseModel {}

    /**
     * @template TViewData as IBaseViewData
     * @template TModel as BaseModel<TViewData>
     */
    abstract class BaseRepository {
        /** @return TViewData */
        abstract public function viewData();
        /** @return TModel */
        abstract public function model();
    }

    class StudentViewData implements IBaseViewData {}
    class TeacherViewData implements IBaseViewData {}

    /** @extends BaseModel<StudentViewData> */
    class StudentModel extends BaseModel {}

    /** @extends BaseModel<TeacherViewData> */
    class TeacherModel extends BaseModel {}

    /** @extends BaseRepository<StudentViewData, StudentModel> */
    abstract class StudentRepository extends BaseRepository {}

    /** @extends BaseRepository<TeacherViewData, TeacherModel> */
    abstract class TeacherRepository extends BaseRepository {}

    function test(StudentRepository $students, TeacherRepository $teachers): void {
        assertType('StudentViewData', $students->viewData());
        assertType('StudentModel', $students->model());
        assertType('TeacherViewData', $teachers->viewData());
        assertType('TeacherModel', $teachers->model());
    }
}

// Test: unwrapIndirectGenericTemplated
namespace PsalmTest_template_nested_template_2 {
    class Payload {}

    /**
     * @template TInner
     */
    interface Wrapper {
        /** @return TInner */
        public function unwrap() : object;
    }

    /**
     * @template TInner2
     * @template TWrapper2 of Wrapper<TInner2>
     * @param  TWrapper2 $wrapper
     * @return TInner2
     */
    function indirectUnwrap(Wrapper $wrapper) : object {
        return unwrapGeneric($wrapper);
    }

    /**
     * @template TInner1
     * @template TWrapper1 of Wrapper<TInner1>
     * @param TWrapper1 $wrapper
     * @return TInner1
     */
    function unwrapGeneric(Wrapper $wrapper) {
        return $wrapper->unwrap();
    }

    /** @param Wrapper<Payload> $wrapper */
    function test(Wrapper $wrapper): void {
        assertType('Payload', $wrapper->unwrap());
        assertType('Payload', unwrapGeneric($wrapper));
        assertType('Payload', indirectUnwrap($wrapper));
    }
}

// Test: unwrapFromTemplatedClassString
namespace PsalmTest_template_nested_template_3 {
    /**
     * @template TInner
     */
    interface Wrapper {
        /** @return TInner */
        public function unwrap();
    }

    /**
     * @implements Wrapper<string>
     */
    class StringWrapper implements Wrapper {
        public function unwrap() {
            return "hello";
        }
    }

    /**
     * @template TInner
     * @template TWrapper of Wrapper<TInner>
     *
     * @param  class-string<TWrapper> $class
     * @return TInner
     */
    function load(string $class) {
        $package = new $class();
        return $package->unwrap();
    }

    $result = load(StringWrapper::class);
    assertType('string', $result);
}

// Test: unwrapNestedTemplateWithReset
namespace PsalmTest_template_nested_template_4 {
    class Item {}

    /**
     * @template TValue
     * @template TArray of non-empty-array<TValue>
     * @param TArray $arr
     * @return TValue
     */
    function toList(array $arr): array {
        return reset($arr);
    }

    /** @param non-empty-array<Item> $items */
    function test(array $items): void {
        assertType('Item', toList($items));
    }
}

// Test: 3levelNestedTemplatesOfMixed
// Upstream's interfaces are empty; J gained a getter so the `@implements
// J<V>` and `@extends J<V>` bindings have something to observe.
namespace PsalmTest_template_nested_template_5 {
    class X {}

    /** @template T */
    interface A {}

    /**
     * @template T
     * @template U of A<T>
     */
    interface B {}

    /** @template T */
    interface J {
        /** @return T */
        public function get();
    }

    /**
     * @template T
     * @template U of A<T>
     * @implements J<U>
     */
    abstract class K2 implements J {}

    /**
     * @template T
     * @template U of A<T>
     * @template V of B<T, U>
     * @extends J<V>
     */
    interface K3 extends J {}

    /**
     * @template T
     * @template U of A<T>
     * @template V of B<T, U>
     * @implements J<V>
     */
    abstract class K1 implements J {}

    /**
     * @param K2<X, A<X>> $k2
     * @param K3<X, A<X>, B<X, A<X>>> $k3
     * @param K1<X, A<X>, B<X, A<X>>> $k1
     */
    function test(K2 $k2, K3 $k3, K1 $k1): void {
        assertType('A<X>', $k2->get());
        assertType('B<X, A<X>>', $k3->get());
        assertType('B<X, A<X>>', $k1->get());
    }
}

// Test: 4levelNestedTemplatesOfObjects
// A concrete subclass was added so the four-level chain of `@extends`
// bindings can be observed through the protected getter.
namespace PsalmTest_template_nested_template_6 {
    /**
     * @template T
     */
    interface DbEntity
    {
        /**
         * @return T
         */
        public function toCore();
    }

    /**
     * @template T of object
     */
    abstract class EntityRepository {}

    /**
     * @template T of object
     * @extends EntityRepository<T>
     */
    abstract class DbEntityRepository
    extends EntityRepository {}

    interface ObjectId {}

    /**
     * @template I of ObjectId
     */
    interface AnObject {}

    /**
     * @template I of ObjectId
     * @template O of AnObject<I>
     * @template E of DbEntity<O>
     * @extends DbEntityRepository<E>
     */
    abstract class AnObjectEntityRepository
    extends DbEntityRepository
    {}

    /**
     * @template T
     * @template E of DbEntity<T>
     * @template R of DbEntityRepository<E>
     */
    abstract class DbRepositoryWrapper
    {
        /** @var R $repo Db repository */
        private DbEntityRepository $repo;

        /**
         * @return DbEntityRepository The Db repository.
         * @psalm-return R
         */
        protected function getDbRepo(): DbEntityRepository
        {
            return $this->repo;
        }
    }

    /**
     * @template I of ObjectId
     * @template O of AnObject<I>
     * @template E of DbEntity<O>
     * @template R of AnObjectEntityRepository<I, O, E>
     * @extends DbRepositoryWrapper<O, E, R>
     */
    abstract class AnObjectDbRepositoryWrapper
    extends DbRepositoryWrapper {}

    class UserId implements ObjectId {}
    /** @implements AnObject<UserId> */
    class User implements AnObject {}
    /** @implements DbEntity<User> */
    abstract class UserEntity implements DbEntity {}
    /** @extends AnObjectEntityRepository<UserId, User, UserEntity> */
    abstract class UserEntityRepository extends AnObjectEntityRepository {}

    /** @extends AnObjectDbRepositoryWrapper<UserId, User, UserEntity, UserEntityRepository> */
    abstract class UserRepository extends AnObjectDbRepositoryWrapper {
        public function test(UserEntity $entity): void {
            assertType('UserEntityRepository', $this->getDbRepo());
            assertType('User', $entity->toCore());
        }
    }
}
