<?php
// Source: Psalm Template/TraitTemplateTest.php
// Hand-ported: the upstream cases are valid-code snippets with no
// assertions, so each assertType() states the type the snippet implies.
// Not generated by scripts/extract_psalm_tests.php.

// Test: traitUseNotExtended
namespace PsalmTest_template_trait_template_1 {
    /**
     * @template T
     */
    trait CollectionTrait
    {
        /**
         * @return array<T>
         */
        abstract function elements() : array;

        /**
         * @return T|null
         */
        public function first()
        {
            return $this->elements()[0] ?? null;
        }
    }

    class Service
    {
        /**
         * @use CollectionTrait<int>
         */
        use CollectionTrait;

        /**
         * @return array<int>
         */
        public function elements(): array
        {
            return [1, 2, 3, 4];
        }
    }

    assertType('int|null', (new Service())->first());
    assertType('array<int>', (new Service())->elements());
}

// Test: extendedTraitUse
namespace PsalmTest_template_trait_template_2 {
    /**
     * @template T
     */
    trait CollectionTrait
    {
        /**
         * @return array<T>
         */
        abstract function elements() : array;

        /**
         * @return T|null
         */
        public function first()
        {
            return $this->elements()[0] ?? null;
        }
    }

    /**
     * @template TValue
     */
    trait BridgeTrait
    {
        /**
         * @use CollectionTrait<TValue>
         */
        use CollectionTrait;
    }

    class Service
    {
        /**
         * @use BridgeTrait<int>
         */
        use BridgeTrait;

        /**
         * @return array<int>
         */
        public function elements(): array
        {
            return [1, 2, 3, 4];
        }
    }

    assertType('int|null', (new Service())->first());
}

// Test: extendedTraitUseAlreadyBound
namespace PsalmTest_template_trait_template_3 {
    /**
     * @template T
     */
    trait CollectionTrait
    {
        /**
         * @return array<T>
         */
        abstract function elements() : array;

        /**
         * @return T|null
         */
        public function first()
        {
            return $this->elements()[0] ?? null;
        }
    }

    trait BridgeTrait
    {
        /**
         * @use CollectionTrait<int>
         */
        use CollectionTrait;
    }

    class Service
    {
        use BridgeTrait;

        /**
         * @return array<int>
         */
        public function elements(): array
        {
            return [1, 2, 3, 4];
        }
    }

    assertType('int|null', (new Service())->first());
}

// Test: badTemplateUseUnionType
namespace PsalmTest_template_trait_template_4 {
    /**
     * @template T
     */
    trait T {
        /** @var T */
        public $t;

        /** @param T $t */
        public function __construct($t) {
            $this->t = $t;
        }
    }

    /**
     * @template TT
     */
    class B {
        /**
         * @template-use T<int|string>
         */
        use T;
    }

    assertType('int|string', (new B(1))->t);
}

// Test: multilineTemplateUse
// Upstream's trait is empty; a getter per template parameter was added so
// the multi-line `@template-use` argument list has something to observe.
namespace PsalmTest_template_trait_template_5 {
    /**
     * @template T1
     * @template T2
     * @template T3
     */
    trait MyTrait {
        /** @return T1 */
        public function first() { return null; }
        /** @return T2 */
        public function second() { return null; }
        /** @return T3 */
        public function third() { return null; }
    }

    class Foo {
        /**
         * @template-use MyTrait<int, string, array{
         * 	foo: mixed,
         * 	bar: mixed,
         * }>
         */
        use MyTrait;
    }

    assertType('int', (new Foo())->first());
    assertType('string', (new Foo())->second());
    assertType('array{foo: mixed, bar: mixed}', (new Foo())->third());
}

// Test: allowTraitExtendAndImplementWithExplicitParamType
namespace PsalmTest_template_trait_template_6 {
    /**
     * @template T
     */
    trait ValueObjectTrait
    {
        /**
         * @psalm-var ?T
         */
        protected $value;

        /**
         * @psalm-param T $value
         *
         * @param $value
         */
        private function setValue($value): void {
            $this->validate($value);

            $this->value = $value;
        }

        /**
         * @psalm-param T $value
         *
         * @param $value
         */
        abstract protected function validate($value): void;
    }

    final class StringValidator {
        /**
         * @template-use ValueObjectTrait<string>
         */
        use ValueObjectTrait;

        /**
         * @param string $value
         */
        protected function validate($value): void
        {
            if (strlen($value) > 30) {
                throw new \Exception("bad");
            }
        }

        public function current(): void
        {
            assertType('string|null', $this->value);
        }
    }
}

// Test: traitInImplicitExtendedClass
namespace PsalmTest_template_trait_template_7 {
    /**
     * @template T
     */
    interface Foo {
        /**
         * @return T
         */
        public function getItem();
    }

    trait FooTrait {
        public function getItem() {
            return "hello";
        }
    }

    /**
     * @template-implements Foo<string>
     */
    class Bar implements Foo {
        use FooTrait;
    }

    assertType('string', (new Bar())->getItem());
}

// Test: useTraitReturnTypeForInheritedInterface
namespace PsalmTest_template_trait_template_8 {
    /**
     * @template TValue
     * @template TNormalizedValue
     */
    interface Normalizer
    {
        /**
         * @param TValue $v
         * @return TNormalizedValue
         */
        function normalize($v);
    }

    /**
     * @template TTraitValue
     * @template TTraitNormalizedValue
     */
    trait NormalizerTrait
    {
        /**
         * @param TTraitValue $v
         * @return TTraitNormalizedValue
         */
        function normalize($v)
        {
            return $this->doNormalize($v);
        }

        /**
         * @param TTraitValue $v
         * @return TTraitNormalizedValue
         */
        abstract protected function doNormalize($v);
    }

    /** @implements Normalizer<string, string> */
    class StringNormalizer implements Normalizer
    {
        /** @use NormalizerTrait<string, string> */
        use NormalizerTrait;

        protected function doNormalize($v): string
        {
            return trim($v);
        }
    }

    assertType('string', (new StringNormalizer())->normalize(' a '));
}

// Test: useTraitReturnTypeForInheritedClass
namespace PsalmTest_template_trait_template_9 {
    /**
     * @template TValue
     * @template TNormalizedValue
     */
    abstract class Normalizer
    {
        /**
         * @param TValue $v
         * @return TNormalizedValue
         */
        abstract function normalize($v);
    }

    /**
     * @template TTraitValue
     * @template TTraitNormalizedValue
     */
    trait NormalizerTrait
    {
        /**
         * @param TTraitValue $v
         * @return TTraitNormalizedValue
         */
        function normalize($v)
        {
            return $this->doNormalize($v);
        }

        /**
         * @param TTraitValue $v
         * @return TTraitNormalizedValue
         */
        abstract protected function doNormalize($v);
    }

    /** @extends Normalizer<string, string> */
    class StringNormalizer extends Normalizer
    {
        /** @use NormalizerTrait<string, string> */
        use NormalizerTrait;

        protected function doNormalize($v): string
        {
            return trim($v);
        }
    }

    assertType('string', (new StringNormalizer())->normalize(' a '));
}

// Test: inheritTraitPropertyTKeyedArray
// Upstream's property is private; it is public here so the substituted
// type can be read from outside the class.
namespace PsalmTest_template_trait_template_10 {
    class Item {}

    /** @template TValue */
    trait A {
        /** @psalm-var array{TValue} */
        public $foo;

        /** @psalm-param array{TValue} $foo */
        public function __construct(array $foo)
        {
            $this->foo = $foo;
        }
    }

    /** @template TValue */
    class B {
        /** @use A<TValue> */
        use A;
    }

    /** @param B<Item> $b */
    function test(B $b): void {
        assertType('array{Item}', $b->foo);
    }
}

// Test: inheritTraitPropertyArray
// Upstream's property is private; it is public here so the substituted
// type can be read from outside the class.
namespace PsalmTest_template_trait_template_11 {
    class Item {}

    /** @template TValue */
    trait A {
        /** @psalm-var array<TValue> */
        public $foo;

        /** @psalm-param array<TValue> $foo */
        public function __construct(array $foo)
        {
            $this->foo = $foo;
        }
    }

    /** @template TValue */
    class B {
        /** @use A<TValue> */
        use A;
    }

    /** @param B<Item> $b */
    function test(B $b): void {
        assertType('array<Item>', $b->foo);
    }
}

// Test: traitSelfAsParam
namespace PsalmTest_template_trait_template_12 {
    trait InstancePool {
        /**
         * @template T as self
         * @param callable():?T $callback
         * @return ?T
         */
        public static function getInstance(callable $callback)
        {
            return $callback();
        }
    }

    class Foo
    {
        use InstancePool;
    }

    assertType('Foo|null', Foo::getInstance(function () {
        return new Foo();
    }));
}

// Test: possiblyNullReferenceOnTraitDefinedMethod
namespace PsalmTest_template_trait_template_13 {
    class Item {}

    /**
     * @template TKey as array-key
     * @template TValue
     */
    trait T1 {
        /**
         * @var array<TKey, TValue>
         */
        protected $mocks = [];

        /**
         * @param TKey $offset
         * @return TValue|null
         */
        public function offsetGet($offset) {
            return $this->mocks[$offset] ?? null;
        }
    }

    /**
     * @template TKey as array-key
     * @template TValue
     */
    interface Arr {
        /**
         * @param TKey $offset
         * @return TValue|null
         */
        public function offsetGet($offset);
    }

    /**
     * @template TKey as array-key
     * @template TValue
     * @implements Arr<TKey, TValue>
     */
    class C implements Arr {
        /** @use T1<TKey, TValue> */
        use T1;
    }

    /** @param C<string, Item> $c */
    function test(C $c): void {
        assertType('Item|null', $c->offsetGet('a'));
    }
}
