<?php
// Source: Psalm TypeReconciliation/ReconcilerTest.php
// Hand-ported: upstream calls AssertionReconciler directly with a synthetic
// assertion; each case here spells that assertion as the PHP condition that
// produces it and asserts the narrowed type inside the branch. Cases whose
// result is a refinement PHPantom treats as its base type (non-empty-*,
// numeric-string, empty-mixed, a literal bool narrowed out of `bool`) are
// left out. Not generated by scripts/extract_psalm_tests.php.

namespace PsalmTest_type_reconciliation_reconciler {
    class SomeClass {}
    class SomeChildClass extends SomeClass {}
    class A {}
    class B {}
    interface SomeInterface {}

    // Test: notNullWithObjectPipeNull
    function notNull(?SomeClass $x): void {
        if ($x !== null) {
            assertType('SomeClass', $x);
        }
    }

    // Test: notNullWithSomeClassPipeFalse
    /** @param SomeClass|false $x */
    function notNullPipeFalse($x): void {
        if ($x !== null) {
            assertType('SomeClass|false', $x);
        }
    }

    // Test: notEmptyWithSomeClassPipeNull, notEmptyWithSomeClassPipeFalse
    /**
     * @param SomeClass|null $a
     * @param SomeClass|false $b
     */
    function truthy($a, $b): void {
        if ($a) {
            assertType('SomeClass', $a);
        }
        if ($b) {
            assertType('SomeClass', $b);
        }
    }

    // Test: nullWithSomeClassPipeNull
    function isNull(?SomeClass $x): void {
        if ($x === null) {
            assertType('null', $x);
        }
    }

    // Test: falsyWithSomeClassPipeFalse, falsyWithSomeClassPipeBool
    /**
     * @param SomeClass|false $a
     * @param SomeClass|bool $b
     */
    function falsy($a, $b): void {
        if (!$a) {
            assertType('false', $a);
        }
        if (!$b) {
            assertType('false', $b);
        }
    }

    // Test: notSomeClassWithSomeClassPipeBool, notSomeClassWithSomeClassPipeNull,
    //       notSomeClassWithAPipeB
    /**
     * @param SomeClass|bool $a
     * @param SomeClass|null $b
     * @param A|B $c
     */
    function notInstanceof($a, $b, $c): void {
        if (!$a instanceof SomeClass) {
            assertType('bool', $a);
        }
        if (!$b instanceof SomeClass) {
            assertType('null', $b);
        }
        if (!$c instanceof A) {
            assertType('B', $c);
        }
    }

    // Test: myObjectWithSomeClassPipeBool, myObjectWithAPipeB
    /**
     * @param SomeClass|bool $a
     * @param A|B $b
     */
    function isInstanceof($a, $b): void {
        if ($a instanceof SomeClass) {
            assertType('SomeClass', $a);
        }
        if ($b instanceof A) {
            assertType('A', $b);
        }
    }

    // Test: array, 2dArray
    /**
     * @param array|null $a
     * @param array<array<string>>|null $b
     */
    function isArray($a, $b): void {
        if (is_array($a)) {
            assertType('array', $a);
        }
        if (is_array($b)) {
            assertType('array<array<string>>', $b);
        }
    }

    // Test: nullableClassString, nullableClassStringFalsy,
    //       nullableClassStringEqualsNull, nullableClassStringTruthy
    /** @param class-string<SomeClass>|null $x */
    function nullableClassString($x): void {
        if (!$x) {
            assertType('null', $x);
        }
        if ($x === null) {
            assertType('null', $x);
        }
        if ($x) {
            assertType('class-string<SomeClass>', $x);
        }
    }

    // Test: iterableToArray, iterableToTraversable, iterableAndObject,
    //       iterableAndNotObject, iterableWithParamsToTraversableWithParams
    /** @param iterable<int, string> $x */
    function iterableNarrowing($x): void {
        if (is_array($x)) {
            assertType('array<int, string>', $x);
        }
        if ($x instanceof \Traversable) {
            assertType('Traversable<int, string>', $x);
        }
        if (is_object($x)) {
            assertType('Traversable<int, string>', $x);
        }
        if (!is_object($x)) {
            assertType('array<int, string>', $x);
        }
        if (!is_array($x)) {
            assertType('Traversable<int, string>', $x);
        }
    }

    // Test: interfaceAssertionOnClassInterfaceUnion,
    //       classAssertionOnClassInterfaceUnion
    /** @param SomeClass|SomeInterface $x */
    function classInterfaceUnion($x): void {
        if ($x instanceof SomeInterface) {
            assertType('SomeClass&SomeInterface|SomeInterface', $x);
        }
        if ($x instanceof SomeClass) {
            assertType('SomeClass|SomeClass&SomeInterface', $x);
        }
    }

    // Test: subclassOfParent (from providerTestTypeIsContainedBy)
    function subclass(SomeClass $x): void {
        if ($x instanceof SomeChildClass) {
            assertType('SomeChildClass', $x);
        }
    }
}

// Test: testReconciliationOfClassConstantInAssertions
// Upstream reconciles a synthetic class-constant assertion; the same types
// are reachable by naming the constants in a `@param`.
namespace PsalmTest_type_reconciliation_reconciler_constants {
    class Foo
    {
        const PREFIX_BAR = 'bar';
        const PREFIX_BAZ = 'baz';
        const PREFIX_QOO = Foo::PREFIX_BAR;
    }

    /**
     * @param Foo::PREFIX_* $prefixed
     * @param Foo::PREFIX_BAR $single
     * @param Foo::PREFIX_QOO $referencing
     * @param Foo::* $all
     * @param Foo::PREFIX_B* $wildcard
     */
    function constants($prefixed, $single, $referencing, $all, $wildcard): void {
        assertType("'bar'|'baz'", $prefixed); // SKIP: a class constant named as a docblock type is not read
        assertType("'bar'", $single); // SKIP: a class constant named as a docblock type is not read
        assertType("'bar'", $referencing); // SKIP: a class constant named as a docblock type is not read
        assertType("'bar'|'baz'", $all); // SKIP: a class constant named as a docblock type is not read
        assertType("'bar'|'baz'", $wildcard); // SKIP: a class constant named as a docblock type is not read
    }
}
