<?php
// Source: Psalm VariadicTest.php
// Hand-ported: the upstream cases are valid-code snippets with no
// assertions, so each assertType() states the type the snippet implies.
// Not generated by scripts/extract_psalm_tests.php.

// Test: variadic
namespace PsalmTest_variadic_1 {
    /**
     * @param mixed $req
     * @param mixed $opt
     * @param mixed ...$params
     * @return array<mixed>
     */
    function f($req, $opt = null, ...$params) {
        assertType('array<int|string, mixed>', $params);
        return $params;
    }

    assertType('array<mixed>', f(1));
    assertType('array<mixed>', f(1, 2, 3, 4, 5));
}

// Test: variadicArray
namespace PsalmTest_variadic_2 {
    /**
     * @param int ...$a_list
     * @return array<array-key, int>
     */
    function f(int ...$a_list) {
        assertType('array<int|string, int>', $a_list);
        return $a_list;
    }

    assertType('array<array-key, int>', f(1, 2, 3));

    /**
     * @param string ...$a_list
     * @return void
     */
    function g(string ...$a_list) {
        assertType('array<int|string, string>', $a_list);
    }
}

// Variadic of a class type: the element type drives member completion on
// each item.
namespace PsalmTest_variadic_3 {
    class Item {}

    function h(Item ...$items): void {
        assertType('array<int|string, Item>', $items);
        foreach ($items as $item) {
            assertType('Item', $item);
        }
    }
}
