use mago_allocator::LocalArena;
use mago_database::file::FileId;
use mago_syntax::cst::*;
use tower_lsp::lsp_types::{Location, Url};

use crate::Backend;
use crate::util::offset_to_position;

use super::helpers::extract_string_literal;

/// Conventional route name suffixes generated by `Route::resource()`.
const RESOURCE_SUFFIXES: &[&str] = &[
    "index", "create", "store", "show", "edit", "update", "destroy",
];

/// Conventional route name suffixes generated by `Route::apiResource()`.
const API_RESOURCE_SUFFIXES: &[&str] = &["index", "store", "show", "update", "destroy"];

/// Derive the route name base from a resource URI string.
///
/// Laravel converts `/` to `.` and uses the result as the name prefix.
/// For example, `"photo-comments"` → `"photo-comments"`,
/// `"photos/comments"` → `"photos.comments"`.
fn resource_name_base(uri: &str) -> String {
    uri.trim_matches('/').replace('/', ".")
}

/// Build the filtered list of resource route suffixes, respecting
/// `->only()` and `->except()` modifiers.
fn filtered_resource_suffixes(
    is_api: bool,
    only: &[String],
    except: &[String],
) -> Vec<&'static str> {
    let base = if is_api {
        API_RESOURCE_SUFFIXES
    } else {
        RESOURCE_SUFFIXES
    };
    base.iter()
        .copied()
        .filter(|s| {
            if !only.is_empty() {
                only.iter().any(|o| o == s)
            } else if !except.is_empty() {
                !except.iter().any(|e| e == s)
            } else {
                true
            }
        })
        .collect()
}

/// Extract string values from `->only()`/`->except()` arguments.
///
/// Handles both array form `->only(['index', 'show'])` and individual
/// args `->except('create', 'edit')`.
fn extract_string_list_from_args<'a>(args: &'a ArgumentList<'a>, content: &'a str) -> Vec<String> {
    let mut values = Vec::new();
    for arg in args.arguments.iter() {
        match arg.value() {
            // Array form: ['index', 'show']
            Expression::Array(arr) => {
                for el in arr.elements.iter() {
                    if let ArrayElement::Value(v) = el
                        && let Some((val, _, _)) = extract_string_literal(v.value, content)
                    {
                        values.push(val.to_string());
                    }
                }
            }
            Expression::LegacyArray(arr) => {
                for el in arr.elements.iter() {
                    if let ArrayElement::Value(v) = el
                        && let Some((val, _, _)) = extract_string_literal(v.value, content)
                    {
                        values.push(val.to_string());
                    }
                }
            }
            // Individual string arg: 'create'
            other => {
                if let Some((val, _, _)) = extract_string_literal(other, content) {
                    values.push(val.to_string());
                }
            }
        }
    }
    values
}

/// Check if a static method call is `Route::resource()` or `Route::apiResource()`
/// and extract the resource name and whether it's an API resource.
fn extract_resource_info<'a>(
    sc: &'a StaticMethodCall<'a>,
    content: &'a str,
) -> Option<(&'a str, usize, bool)> {
    let ClassLikeMemberSelector::Identifier(ident) = &sc.method else {
        return None;
    };
    let method_lower = ident.value.to_ascii_lowercase();
    let is_api = if method_lower == b"resource" {
        false
    } else if method_lower == b"apiresource" {
        true
    } else {
        return None;
    };
    let first_arg = sc.argument_list.arguments.iter().next()?;
    let (res_name, start, _) = extract_string_literal(first_arg.value(), content)?;
    Some((res_name, start, is_api))
}

/// Resolve `route('name')` to the `->name('name')` declaration in `routes/`.
///
/// Supports both explicit full-name declarations:
///   `Route::get('/create', ...)->name('admin.email.template.create')`
///
/// And group prefix notation:
///   `Route::name('admin.email.template.')->group(fn() { Route::get(...)->name('create'); })`
pub(crate) fn resolve_route_definitions(backend: &Backend, name: &str) -> Vec<Location> {
    let mut results = Vec::new();
    let snapshot = backend.user_file_symbol_maps();

    for (file_uri, _) in snapshot {
        if !file_uri.contains("/routes/") {
            continue;
        }
        let Ok(uri) = Url::parse(&file_uri) else {
            continue;
        };
        let Some(content) = backend.get_file_content(&file_uri) else {
            continue;
        };
        let file_dir = uri
            .to_file_path()
            .ok()
            .and_then(|p| p.parent().map(|d| d.to_path_buf()));
        results.extend(scan_route_file(&content, name, &uri, file_dir.as_deref()));
    }

    for route_path in &backend.laravel_provider_resources.read().route_files {
        if let Ok(content) = std::fs::read_to_string(route_path)
            && let Ok(uri) = Url::from_file_path(route_path)
        {
            let file_dir = route_path.parent();
            results.extend(scan_route_file(&content, name, &uri, file_dir));
        }
    }

    results
}

// ─── Route file scanner ──────────────────────────────────────────────────────

fn scan_route_file(
    content: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    let arena = LocalArena::new();
    let file_id = FileId::new(b"input.php");
    let program = mago_syntax::parser::parse_file_content(&arena, file_id, content.as_bytes());
    let mut results = Vec::new();

    for stmt in program.statements.iter() {
        results.extend(scan_stmt(stmt, content, "", target, uri, file_dir));
    }
    results
}

fn scan_stmt<'a>(
    stmt: &Statement<'a>,
    content: &str,
    prefix: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    match stmt {
        Statement::Expression(e) => scan_expr(e.expression, content, prefix, target, uri, file_dir),
        Statement::Return(r) => r
            .value
            .map(|v| scan_expr(v, content, prefix, target, uri, file_dir))
            .unwrap_or_default(),
        _ => Vec::new(),
    }
}

/// Walk a call-chain expression while tracking the accumulated group name prefix.
///
/// Handles two forms of group calls:
/// - Fluent chain: `Route::name('prefix.')->middleware(…)->group(fn(){…})`
///   (outermost node is `Call::Method`)
/// - Direct static: `Route::group(['as'=>'prefix.', …], fn(){…})`
///   (outermost node is `Call::StaticMethod`)
fn scan_expr<'a>(
    expr: &Expression<'a>,
    content: &str,
    prefix: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    match expr {
        // ── Fluent instance-method chain: ->group() / ->name() / other ──────
        Expression::Call(Call::Method(mc)) => {
            let mut results = Vec::new();
            let ClassLikeMemberSelector::Identifier(ident) = &mc.method else {
                return scan_expr(mc.object, content, prefix, target, uri, file_dir);
            };
            let method = ident.value.to_ascii_lowercase();

            if method == b"group" {
                let chain_prefix = chain_name_prefix(mc.object, content);
                let new_prefix = format!("{prefix}{chain_prefix}");
                for arg in mc.argument_list.arguments.iter() {
                    results.extend(scan_group_body(
                        arg.value(),
                        content,
                        &new_prefix,
                        target,
                        uri,
                        file_dir,
                    ));
                }
            } else if method == b"name" {
                if let Some(first_arg) = mc.argument_list.arguments.iter().next()
                    && let Some((name_val, start, _)) =
                        extract_string_literal(first_arg.value(), content)
                {
                    let full = format!("{prefix}{name_val}");
                    if full == target {
                        results.push(crate::definition::point_location(
                            uri.clone(),
                            offset_to_position(content, start),
                        ));
                    }
                }
                results.extend(scan_expr(mc.object, content, prefix, target, uri, file_dir));
            } else if method == b"only" || method == b"except" {
                // ->only(['index', 'show']) or ->except(['create', 'edit'])
                // on a Route::resource() / Route::apiResource() call.
                if let Expression::Call(Call::StaticMethod(sc)) = mc.object
                    && let Some((res_name, start, is_api)) = extract_resource_info(sc, content)
                {
                    let filter = extract_string_list_from_args(&mc.argument_list, content);
                    let (only, except) = if method == b"only" {
                        (filter, Vec::new())
                    } else {
                        (Vec::new(), filter)
                    };
                    let suffixes = filtered_resource_suffixes(is_api, &only, &except);
                    let base = resource_name_base(res_name);
                    for suffix in suffixes {
                        let full = format!("{prefix}{base}.{suffix}");
                        if full == target {
                            return vec![crate::definition::point_location(
                                uri.clone(),
                                offset_to_position(content, start),
                            )];
                        }
                    }
                    return Vec::new();
                }
                results.extend(scan_expr(mc.object, content, prefix, target, uri, file_dir));
            } else {
                results.extend(scan_expr(mc.object, content, prefix, target, uri, file_dir));
            }
            results
        }

        // ── Direct static call: Route::group / Route::resource / Route::apiResource
        Expression::Call(Call::StaticMethod(sc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &sc.method else {
                return Vec::new();
            };
            let method_lower = ident.value.to_ascii_lowercase();

            if method_lower == b"group" {
                let mut results = Vec::new();
                let array_prefix = extract_as_prefix_from_args(
                    sc.argument_list.arguments.iter().map(|a| a.value()),
                    content,
                );
                let new_prefix = format!("{prefix}{array_prefix}");
                for arg in sc.argument_list.arguments.iter() {
                    results.extend(scan_group_body(
                        arg.value(),
                        content,
                        &new_prefix,
                        target,
                        uri,
                        file_dir,
                    ));
                }
                results
            } else if method_lower == b"resource" || method_lower == b"apiresource" {
                // Route::resource('presses', Controller::class) generates
                // conventional named routes like presses.index, presses.show, etc.
                let suffixes = if method_lower == b"resource" {
                    RESOURCE_SUFFIXES
                } else {
                    API_RESOURCE_SUFFIXES
                };
                if let Some(first_arg) = sc.argument_list.arguments.iter().next()
                    && let Some((res_name, start, _)) =
                        extract_string_literal(first_arg.value(), content)
                {
                    let base = resource_name_base(res_name);
                    for suffix in suffixes {
                        let full = format!("{prefix}{base}.{suffix}");
                        if full == target {
                            return vec![crate::definition::point_location(
                                uri.clone(),
                                offset_to_position(content, start),
                            )];
                        }
                    }
                }
                Vec::new()
            } else {
                Vec::new()
            }
        }

        _ => Vec::new(),
    }
}

/// Walk the argument that was passed to `->group()`.
///
/// Handles closures, arrow functions, and `__DIR__ . '/sub.php'` file
/// includes so that go-to-definition works on route names defined in
/// included sub-files.
fn scan_group_body<'a>(
    expr: &Expression<'a>,
    content: &str,
    prefix: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    match expr {
        Expression::Closure(closure) => {
            let mut results = Vec::new();
            for stmt in closure.body.statements.iter() {
                results.extend(scan_stmt(stmt, content, prefix, target, uri, file_dir));
            }
            results
        }
        Expression::ArrowFunction(af) => {
            scan_expr(af.expression, content, prefix, target, uri, file_dir)
        }
        _ => {
            // Follow `Route::group([], __DIR__ . '/sub.php')` file includes.
            // Parse the included file and scan it with the current prefix
            // so routes inherit the parent group's name prefix.
            // (Do NOT call `scan_route_file` — it resets the prefix to "".)
            if let Some(dir) = file_dir
                && let Some(rel_path) = extract_dir_concat_path(expr, content)
            {
                let included = dir.join(rel_path.trim_start_matches('/'));
                if let Ok(ref included_content) = std::fs::read_to_string(&included) {
                    let sub_uri = Url::from_file_path(&included).unwrap_or_else(|_| uri.clone());
                    let sub_dir = included.parent().map(|d| d.to_path_buf());
                    let arena = LocalArena::new();
                    let fid = FileId::new(b"included.php");
                    let prog = mago_syntax::parser::parse_file_content(
                        &arena,
                        fid,
                        included_content.as_bytes(),
                    );
                    let mut results = Vec::new();
                    for stmt in prog.statements.iter() {
                        results.extend(scan_stmt(
                            stmt,
                            included_content,
                            prefix,
                            target,
                            &sub_uri,
                            sub_dir.as_deref(),
                        ));
                    }
                    return results;
                }
            }
            Vec::new()
        }
    }
}

/// Collect all route names defined in `routes/` files.
///
/// Returns a sorted, deduplicated list of fully-qualified route names
/// (e.g. `["admin.dashboard", "admin.users.index", "home"]`).
///
/// Follows `Route::group([], __DIR__ . '/sub.php')` file includes so
/// that routes in sub-files inherit the parent group's name prefix.
pub(crate) fn enumerate_all_route_names(backend: &Backend) -> Vec<String> {
    let mut names = Vec::new();
    let snapshot = backend.user_file_symbol_maps();

    for (file_uri, _) in snapshot {
        if !file_uri.contains("/routes/") {
            continue;
        }
        // Skip sub-directory route files at the top level — they are
        // included by parent files via `Route::group([], __DIR__ . '/sub.php')`
        // and should only be scanned in that context to inherit the
        // correct name prefix.  A "sub-directory" file is one where the
        // path after the last `/routes/` segment contains another `/`.
        if let Some(after) = file_uri.rsplit("/routes/").next()
            && after.contains('/')
        {
            continue;
        }
        let Some(content) = backend.get_file_content(&file_uri) else {
            continue;
        };
        let file_dir = Url::parse(&file_uri)
            .ok()
            .and_then(|u| u.to_file_path().ok())
            .and_then(|p| p.parent().map(|d| d.to_path_buf()));
        collect_all_names_from_file(&content, file_dir.as_deref(), &mut names);
    }

    for route_path in &backend.laravel_provider_resources.read().route_files {
        if let Ok(content) = std::fs::read_to_string(route_path) {
            let file_dir = route_path.parent();
            collect_all_names_from_file(&content, file_dir, &mut names);
        }
    }

    names.sort();
    names.dedup();
    names
}

/// Parse a single route file and collect every `->name('...')` value,
/// accounting for group prefixes and file includes.
fn collect_all_names_from_file(
    content: &str,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<String>,
) {
    let arena = LocalArena::new();
    let file_id = FileId::new(b"input.php");
    let program = mago_syntax::parser::parse_file_content(&arena, file_id, content.as_bytes());
    for stmt in program.statements.iter() {
        collect_names_from_stmt(stmt, content, "", file_dir, out);
    }
}

fn collect_names_from_stmt<'a>(
    stmt: &Statement<'a>,
    content: &str,
    prefix: &str,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<String>,
) {
    match stmt {
        Statement::Expression(e) => {
            collect_names_from_expr(e.expression, content, prefix, file_dir, out);
        }
        Statement::Return(r) => {
            if let Some(v) = r.value {
                collect_names_from_expr(v, content, prefix, file_dir, out);
            }
        }
        _ => {}
    }
}

fn collect_names_from_expr<'a>(
    expr: &Expression<'a>,
    content: &str,
    prefix: &str,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<String>,
) {
    match expr {
        Expression::Call(Call::Method(mc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &mc.method else {
                collect_names_from_expr(mc.object, content, prefix, file_dir, out);
                return;
            };
            let method = ident.value.to_ascii_lowercase();

            if method == b"group" {
                let chain_prefix = chain_name_prefix(mc.object, content);
                let new_prefix = format!("{prefix}{chain_prefix}");
                for arg in mc.argument_list.arguments.iter() {
                    collect_names_from_group_body(arg.value(), content, &new_prefix, file_dir, out);
                }
            } else if method == b"name" {
                if let Some(first_arg) = mc.argument_list.arguments.iter().next()
                    && let Some((name_val, _, _)) =
                        extract_string_literal(first_arg.value(), content)
                {
                    let full = format!("{prefix}{name_val}");
                    // Only collect leaf names (non-prefix names that don't end with '.').
                    if !full.is_empty() && !full.ends_with('.') {
                        out.push(full);
                    }
                }
                collect_names_from_expr(mc.object, content, prefix, file_dir, out);
            } else if method == b"only" || method == b"except" {
                // ->only() / ->except() on Route::resource() / apiResource()
                if let Expression::Call(Call::StaticMethod(sc)) = mc.object
                    && let Some((res_name, _, is_api)) = extract_resource_info(sc, content)
                {
                    let filter = extract_string_list_from_args(&mc.argument_list, content);
                    let (only, except) = if method == b"only" {
                        (filter, Vec::new())
                    } else {
                        (Vec::new(), filter)
                    };
                    let suffixes = filtered_resource_suffixes(is_api, &only, &except);
                    let base = resource_name_base(res_name);
                    for suffix in suffixes {
                        let full = format!("{prefix}{base}.{suffix}");
                        out.push(full);
                    }
                    return;
                }
                collect_names_from_expr(mc.object, content, prefix, file_dir, out);
            } else {
                collect_names_from_expr(mc.object, content, prefix, file_dir, out);
            }
        }
        Expression::Call(Call::StaticMethod(sc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &sc.method else {
                return;
            };
            let method_lower = ident.value.to_ascii_lowercase();

            if method_lower == b"group" {
                let array_prefix = extract_as_prefix_from_args(
                    sc.argument_list.arguments.iter().map(|a| a.value()),
                    content,
                );
                let new_prefix = format!("{prefix}{array_prefix}");
                for arg in sc.argument_list.arguments.iter() {
                    collect_names_from_group_body(arg.value(), content, &new_prefix, file_dir, out);
                }
            } else if method_lower == b"resource" || method_lower == b"apiresource" {
                // Route::resource('presses', Controller::class) without only/except
                // generates all conventional route names.
                if let Some((res_name, _, is_api)) = extract_resource_info(sc, content) {
                    let suffixes = filtered_resource_suffixes(is_api, &[], &[]);
                    let base = resource_name_base(res_name);
                    for suffix in suffixes {
                        let full = format!("{prefix}{base}.{suffix}");
                        out.push(full);
                    }
                }
            }
        }
        _ => {}
    }
}

fn collect_names_from_group_body<'a>(
    expr: &Expression<'a>,
    content: &str,
    prefix: &str,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<String>,
) {
    match expr {
        Expression::Closure(closure) => {
            for stmt in closure.body.statements.iter() {
                collect_names_from_stmt(stmt, content, prefix, file_dir, out);
            }
        }
        Expression::ArrowFunction(af) => {
            collect_names_from_expr(af.expression, content, prefix, file_dir, out);
        }
        _ => {
            // Handle `Route::group([], __DIR__ . '/sub.php')` file includes.
            // The expression is a binary concatenation: `__DIR__ . '/path'`.
            if let Some(dir) = file_dir
                && let Some(rel_path) = extract_dir_concat_path(expr, content)
            {
                let included = dir.join(rel_path.trim_start_matches('/'));
                if let Ok(included_content) = std::fs::read_to_string(&included) {
                    let sub_dir = included.parent().map(|d| d.to_path_buf());
                    // Scan the included file with the current prefix so
                    // routes inherit the parent group's name (e.g.
                    // "eaglesys::").  Do NOT scan with empty prefix —
                    // that produces unprefixed names that are incorrect.
                    let arena2 = LocalArena::new();
                    let fid2 = FileId::new(b"included.php");
                    let prog2 = mago_syntax::parser::parse_file_content(
                        &arena2,
                        fid2,
                        included_content.as_bytes(),
                    );
                    for stmt in prog2.statements.iter() {
                        collect_names_from_stmt(
                            stmt,
                            &included_content,
                            prefix,
                            sub_dir.as_deref(),
                            out,
                        );
                    }
                }
            }
        }
    }
}

use super::helpers::extract_dir_concat_path;

pub(crate) use super::helpers::{chain_name_prefix, extract_as_prefix_from_args};
