use std::cell::RefCell;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use mago_allocator::LocalArena;
use mago_database::file::FileId;
use mago_span::HasSpan;
use mago_syntax::cst::*;
use tower_lsp::lsp_types::{Location, Url};

use crate::Backend;
use crate::atom::bytes_to_str;
use crate::text_position::offset_to_position;

use super::const_eval::{Scope, bind_assignment, const_string, for_each_iteration};
use super::helpers::{
    chain_as_prefix, chain_dynamic_name_prefix, dynamic_as_prefix_from_args,
    extract_string_literal, first_string_arg, singularize_english_word,
};
use super::provider_resources::resolve_path_arg;

/// Conventional route name suffixes generated by `Route::resource()`.
const RESOURCE_SUFFIXES: &[&str] = &[
    "index", "create", "store", "show", "edit", "update", "destroy",
];

/// Conventional route name suffixes generated by `Route::apiResource()`.
const API_RESOURCE_SUFFIXES: &[&str] = &["index", "store", "show", "update", "destroy"];

/// Whether `name` is one of the routes `pattern` names.
///
/// Most call sites write the name of exactly one route, and there `pattern`
/// is that name.  The "is the current route named …?" checks
/// (`Route::is('admin.*')`, `$request->routeIs('order.*')`) instead write a
/// pattern, which Laravel matches with `Str::is()`: `*` stands for any run of
/// characters and everything else is literal.
pub(crate) fn route_name_matches(pattern: &str, name: &str) -> bool {
    if !pattern.contains('*') {
        return pattern == name;
    }
    let mut segments = pattern.split('*').peekable();
    // Everything before the first `*` has to be exactly where it is written.
    let Some(mut rest) = segments.next().and_then(|head| name.strip_prefix(head)) else {
        return false;
    };
    while let Some(segment) = segments.next() {
        // Everything after the last `*` has to end the name; a pattern that
        // ends in one has an empty final segment, which every name ends with.
        if segments.peek().is_none() {
            return rest.ends_with(segment);
        }
        // A segment between two stars may start anywhere after the one
        // before it, and taking its earliest match is safe: a later one
        // only leaves less room for the segments that follow.
        let Some(index) = rest.find(segment) else {
            return false;
        };
        rest = &rest[index + segment.len()..];
    }
    true
}

/// Split a resource name on `/` into the URI prefix it implies and the
/// resource itself.
///
/// Laravel's `ResourceRegistrar` treats a slash in the name as a request to
/// wrap the resource in a prefixed group, so `Route::resource('photos/comments')`
/// registers the resource `comments` under the URI prefix `photos` — the names
/// it generates are `comments.index`, not `photos.comments.index`.
fn split_resource_prefix(name: &str) -> (&str, &str) {
    let name = name.trim_matches('/');
    match name.rsplit_once('/') {
        Some((prefix, resource)) => (prefix, resource),
        None => ("", name),
    }
}

/// Whether a `->shallow(…)` link turns shallow routing on.
///
/// The argument defaults to `true` and is read when present, so
/// `->shallow(false)` leaves a nested resource nested.  A non-literal
/// argument is a value we cannot evaluate; Laravel's own default is the
/// better guess than silently dropping the parent segments.
fn shallow_argument(args: &ArgumentList<'_>) -> bool {
    let Some(argument) = args.arguments.iter().next() else {
        return true;
    };
    !matches!(argument.value(), Expression::Literal(Literal::False(_)))
}

/// Build the filtered list of resource route suffixes, respecting
/// `->only()` and `->except()` modifiers.
///
/// `apiResource()` is expressed by the framework as an implicit
/// `only` of the five API methods, so an explicit `->only()` *replaces* it
/// and can bring `create`/`edit` back, while `->except()` narrows whichever
/// set is in force.  Both are applied, in that order, exactly as
/// `getResourceMethods()` does.
fn filtered_resource_suffixes(
    is_api: bool,
    only: Option<&[String]>,
    except: Option<&[String]>,
) -> Vec<&'static str> {
    RESOURCE_SUFFIXES
        .iter()
        .copied()
        .filter(|suffix| match only {
            Some(only) => only.iter().any(|o| o == suffix),
            None => !is_api || API_RESOURCE_SUFFIXES.contains(suffix),
        })
        .filter(|suffix| match except {
            Some(except) => !except.iter().any(|e| e == suffix),
            None => true,
        })
        .collect()
}

/// Extract string values from `->only()`/`->except()` arguments.
///
/// Handles both array form `->only(['index', 'show'])` and individual
/// args `->except('create', 'edit')`.
fn extract_string_list_from_args<'a>(args: &'a ArgumentList<'a>, content: &'a str) -> Vec<String> {
    let mut values = Vec::new();
    for arg in args.arguments.iter() {
        match arg.value() {
            // Array form: ['index', 'show']
            Expression::Array(arr) => {
                for el in arr.elements.iter() {
                    if let ArrayElement::Value(v) = el
                        && let Some((val, _, _)) = extract_string_literal(v.value, content)
                    {
                        values.push(val.to_string());
                    }
                }
            }
            Expression::LegacyArray(arr) => {
                for el in arr.elements.iter() {
                    if let ArrayElement::Value(v) = el
                        && let Some((val, _, _)) = extract_string_literal(v.value, content)
                    {
                        values.push(val.to_string());
                    }
                }
            }
            // Individual string arg: 'create'
            other => {
                if let Some((val, _, _)) = extract_string_literal(other, content) {
                    values.push(val.to_string());
                }
            }
        }
    }
    values
}

/// Extract the key/value string pairs of an array argument, as
/// `->parameters(['photos' => 'grid'])` passes.
fn extract_string_pairs_from_args(args: &ArgumentList<'_>, content: &str) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    for arg in args.arguments.iter() {
        let elements = match arg.value() {
            Expression::Array(arr) => arr.elements.as_slice(),
            Expression::LegacyArray(arr) => arr.elements.as_slice(),
            _ => continue,
        };
        for el in elements {
            if let ArrayElement::KeyValue(kv) = el
                && let Some((key, _, _)) = extract_string_literal(kv.key, content)
                && let Some((value, _, _)) = extract_string_literal(kv.value, content)
            {
                pairs.push((key.to_string(), value.to_string()));
            }
        }
    }
    pairs
}

/// A `Route::resource()` / `Route::apiResource()` registration, together with
/// the chain modifiers that shape the routes it generates.
struct ResourceRegistration<'a> {
    /// The resource name exactly as written (`photos`, `photos.comments`).
    name: &'a str,
    /// Byte offset of the resource-name string literal, for go-to-definition.
    name_offset: usize,
    /// `true` for `apiResource()`, which omits the `create` and `edit` routes.
    is_api: bool,
    /// Route suffixes kept by `->only([…])`; `None` when never called, which
    /// differs from `->only([])` — that registers nothing at all.
    only: Option<Vec<String>>,
    /// Route suffixes dropped by `->except([…])`; `None` when never called.
    except: Option<Vec<String>>,
    /// `->parameters(['photos' => 'grid'])` wildcard-name overrides, keyed by
    /// the resource-name segment they replace.
    parameters: Vec<(String, String)>,
    /// `->shallow()`: the routes that identify a child by its own id drop the
    /// parent segments of a nested resource.  `->shallow(false)` turns it back
    /// off, so the argument is read rather than assumed.
    shallow: bool,
    /// `->as('admin')` / `->name('admin')` ahead of the registration, which
    /// prefixes every generated route name.
    name_prefix: Option<String>,
    /// `->names('images')`: the name every generated route is built from,
    /// replacing the resource name.
    names_all: Option<String>,
    /// `->names(['index' => '…'])` / `->name('index', '…')`: a whole route
    /// name for one method, which bypasses the `->as()` prefix entirely.
    names_by_method: Vec<(String, String)>,
    /// The chain ahead of the `resource()` call, kept so a `->group()` that
    /// shares the chain still has its body walked — `RouteRegistrar::group()`
    /// returns the registrar, so the two can legally be written together.
    preceding: Option<&'a Expression<'a>>,
}

/// Recognise a `resource()` / `apiResource()` call from its method selector
/// and arguments, whichever side of the chain it sits on.
///
/// This runs for every link of every call chain in a route file, so the method
/// name is compared in place rather than lowercased into a fresh allocation.
fn resource_call_info<'a>(
    method: &ClassLikeMemberSelector<'a>,
    args: &'a ArgumentList<'a>,
    content: &'a str,
) -> Option<(&'a str, usize, bool)> {
    let ClassLikeMemberSelector::Identifier(ident) = method else {
        return None;
    };
    let is_api = if ident.value.eq_ignore_ascii_case(b"resource") {
        false
    } else if ident.value.eq_ignore_ascii_case(b"apiResource") {
        true
    } else {
        return None;
    };
    let (res_name, start, _) =
        extract_string_literal(args.arguments.iter().next()?.value(), content)?;
    Some((res_name, start, is_api))
}

/// Recover the resource registration a call chain expresses, if any.
///
/// The registration call may be the static entry point
/// (`Route::resource('photos', …)`) or a link further along the chain
/// (`Route::prefix('admin')->resource('photos', …)`), and the modifiers that
/// follow it (`->only()`, `->parameters()`, `->shallow()`) are collected on
/// the way back out.  Returns `None` for any chain that registers no resource.
fn resource_registration<'a>(
    expr: &'a Expression<'a>,
    content: &'a str,
) -> Option<ResourceRegistration<'a>> {
    let new_registration =
        |(name, name_offset, is_api), name_prefix, preceding| ResourceRegistration {
            name,
            name_offset,
            is_api,
            only: None,
            except: None,
            parameters: Vec::new(),
            shallow: false,
            name_prefix,
            names_all: None,
            names_by_method: Vec::new(),
            preceding,
        };

    match expr {
        Expression::Call(Call::StaticMethod(sc)) => {
            resource_call_info(&sc.method, &sc.argument_list, content)
                .map(|info| new_registration(info, None, None))
        }
        Expression::Call(Call::Method(mc)) => {
            if let Some(info) = resource_call_info(&mc.method, &mc.argument_list, content) {
                // Anything ahead of the registration in the chain can only
                // contribute a route-name prefix.  A `->prefix()` there is
                // dropped on the floor by `ResourceRegistrar`, which never
                // copies it into the action, so it is deliberately not read.
                return Some(new_registration(
                    info,
                    chain_as_prefix(mc.object, content),
                    Some(mc.object),
                ));
            }
            let mut registration = resource_registration(mc.object, content)?;
            let ClassLikeMemberSelector::Identifier(ident) = &mc.method else {
                return Some(registration);
            };
            let method = ident.value;
            if method.eq_ignore_ascii_case(b"only") {
                registration.only = Some(extract_string_list_from_args(&mc.argument_list, content));
            } else if method.eq_ignore_ascii_case(b"except") {
                registration.except =
                    Some(extract_string_list_from_args(&mc.argument_list, content));
            } else if method.eq_ignore_ascii_case(b"names") {
                // `->names('images')` renames the resource; `->names([...])`
                // sets whole route names per method.
                let pairs = extract_string_pairs_from_args(&mc.argument_list, content);
                if pairs.is_empty() {
                    registration.names_all = first_string_arg(&mc.argument_list, content)
                        .map(str::to_string)
                        .or(registration.names_all);
                } else {
                    registration.names_by_method.extend(pairs);
                }
            } else if method.eq_ignore_ascii_case(b"parameters") {
                registration.parameters =
                    extract_string_pairs_from_args(&mc.argument_list, content);
            } else if method.eq_ignore_ascii_case(b"parameter") {
                // `->parameter('photos', 'grid')` overrides a single wildcard.
                let mut args = mc.argument_list.arguments.iter();
                if let Some((key, _, _)) = args
                    .next()
                    .and_then(|a| extract_string_literal(a.value(), content))
                    && let Some((value, _, _)) = args
                        .next()
                        .and_then(|a| extract_string_literal(a.value(), content))
                {
                    registration
                        .parameters
                        .push((key.to_string(), value.to_string()));
                }
            } else if method.eq_ignore_ascii_case(b"name") {
                // On a resource chain `->name()` takes a method and the whole
                // route name to give it, unlike the `->name()` that prefixes a
                // group.
                let mut args = mc.argument_list.arguments.iter();
                if let Some((method_name, _, _)) = args
                    .next()
                    .and_then(|a| extract_string_literal(a.value(), content))
                    && let Some((route_name, _, _)) = args
                        .next()
                        .and_then(|a| extract_string_literal(a.value(), content))
                {
                    registration
                        .names_by_method
                        .push((method_name.to_string(), route_name.to_string()));
                }
            } else if method.eq_ignore_ascii_case(b"shallow") {
                registration.shallow = shallow_argument(&mc.argument_list);
            }
            Some(registration)
        }
        _ => None,
    }
}

/// The wildcard Laravel derives for one segment of a resource name.
///
/// `photos` yields `{photo}`; `->parameters(['photos' => 'grid'])` replaces the
/// derived name, and hyphens become underscores so the result is a legal
/// parameter name.
fn resource_wildcard(segment: &str, overrides: &[(String, String)]) -> String {
    // Searched from the end: `->parameters([…])` replaces the whole map while
    // `->parameter(…)` appends to it, so the last entry for a segment is the
    // one the chain settled on.
    let name = overrides
        .iter()
        .rev()
        .find(|(key, _)| key == segment)
        .map(|(_, value)| value.clone())
        .unwrap_or_else(|| singularize_english_word(segment));
    if name.as_bytes().contains(&b'-') {
        name.replace('-', "_")
    } else {
        name
    }
}

/// The URI a resource name maps to, before any per-route suffix.
///
/// `photos.comments` becomes `photos/{photo}/comments` — the last segment's
/// wildcard belongs to the individual routes that identify a single record.
///
/// Laravel builds this by giving *every* segment a wildcard and then deleting
/// the last segment's wildcard from the result, and the deletion is not
/// anchored to the end.  A resource whose segments singularize alike
/// (`company.companies`, both `{company}`) therefore loses both wildcards and
/// comes out as `company/companies`, which is reproduced here rather than
/// tidied up.
fn nested_resource_uri(segments: &[&str], overrides: &[(String, String)]) -> String {
    let mut uri = String::new();
    for (i, segment) in segments.iter().enumerate() {
        if i > 0 {
            uri.push('/');
        }
        uri.push_str(segment);
        uri.push_str("/{");
        uri.push_str(&resource_wildcard(segment, overrides));
        uri.push('}');
    }
    let Some(last) = segments.last() else {
        return uri;
    };
    uri.replace(&format!("/{{{}}}", resource_wildcard(last, overrides)), "")
}

// ─── Route source traversal ──────────────────────────────────────────────────

/// Where a route source sits on disk, and which files the chain of includes
/// reaching it has already opened.
///
/// `dir` anchors `__DIR__`-relative paths and `root` anchors `base_path()`
/// ones.  `open` is the cycle breaker: route files legitimately pull each
/// other in, and following a `require` back into a file already on the
/// include stack would not terminate.  `program` is the parse of the source
/// being scanned, which is what lets an include target written as a local
/// variable be followed back to the path it was assigned; every hop that
/// switches source (an included file, a macro body) replaces it along with
/// `dir`.
#[derive(Clone, Copy)]
struct ScanPaths<'a> {
    dir: Option<&'a Path>,
    root: Option<&'a Path>,
    open: &'a RefCell<HashSet<PathBuf>>,
    macros: &'a MacroScope,
    program: &'a Program<'a>,
    /// The file the walk is currently reading, which is where the route names
    /// it finds are declared.
    uri: &'a Url,
}

impl<'a> ScanPaths<'a> {
    fn new(
        dir: Option<&'a Path>,
        root: Option<&'a Path>,
        open: &'a RefCell<HashSet<PathBuf>>,
        macros: &'a MacroScope,
        program: &'a Program<'a>,
        uri: &'a Url,
    ) -> Self {
        Self {
            dir,
            root,
            open,
            macros,
            program,
            uri,
        }
    }
}

/// Parse a route file and hand the program to `walk`.
///
/// The arena the program is allocated in lives only as long as the call, so
/// every walk of a file — the route file itself, one it includes, a macro
/// body — runs inside one of these rather than holding the program.
fn in_parsed_route_file<R>(
    content: &str,
    name: &'static [u8],
    walk: impl FnOnce(&Program<'_>) -> R,
) -> R {
    let arena = LocalArena::new();
    let file_id = FileId::new(name);
    let program = mago_syntax::parser::parse_file_content(&arena, file_id, content.as_bytes());
    walk(program)
}

// ─── Router macros ───────────────────────────────────────────────────────────

/// The classes a route-registering macro attaches to.
///
/// `Route::macro('auth', …)` records the facade, and the macro index carries a
/// second copy targeting the concrete router the facade proxies.
/// `Route::mixin(new AuthRouteMethods)` — how `laravel/ui` ships
/// `Route::auth()` — lands on the same pair.
const ROUTER_MACRO_TARGETS: &[&str] = &[
    "Illuminate\\Support\\Facades\\Route",
    "Illuminate\\Routing\\Router",
    "Illuminate\\Routing\\RouteRegistrar",
];

/// The router macros a scan may need to expand, and the state of the scan's
/// expansions so far.
///
/// A route file that calls `Route::auth()` registers whatever that macro's
/// closure registers, but the closure lives outside the route tree (in a
/// service provider, or in a mixin class a provider passes to
/// `Route::mixin()`).  This resolves such calls through the project's macro
/// index and reads the file holding the body on demand, so a project with no
/// router macros pays only for the (empty) lookup table.
#[derive(Default)]
struct MacroScope {
    /// Lowercased macro name → the URI of the file its closure was written in
    /// and the closure's byte offset there.
    bodies: HashMap<String, (String, u32)>,
    /// The macro names on the expansion stack.  `Route::auth()` calls
    /// `$this->resetPassword()`, so bodies legitimately nest; this is what
    /// stops a macro that reaches itself again from recursing forever.
    expanding: RefCell<HashSet<String>>,
    /// Source of each macro file, read once per scan.  `None` records a file
    /// that could not be read so the failure is not retried.
    sources: RefCell<HashMap<String, Option<Arc<str>>>>,
}

impl MacroScope {
    /// The router macros registered in `backend`'s project.
    fn for_backend(backend: &Backend) -> Self {
        if !backend
            .laravel_has_macros
            .load(std::sync::atomic::Ordering::Relaxed)
        {
            return Self::default();
        }
        Self {
            bodies: backend
                .laravel_macros
                .read()
                .macro_closures_on(ROUTER_MACRO_TARGETS),
            ..Self::default()
        }
    }

    /// Read (and memoize) the source of the file a macro closure lives in.
    fn source(&self, uri: &str) -> Option<Arc<str>> {
        if let Some(cached) = self.sources.borrow().get(uri) {
            return cached.clone();
        }
        let loaded = Url::parse(uri)
            .ok()
            .and_then(|url| url.to_file_path().ok())
            .and_then(|path| std::fs::read_to_string(path).ok())
            .map(Arc::<str>::from);
        self.sources
            .borrow_mut()
            .insert(uri.to_string(), loaded.clone());
        loaded
    }
}

/// A router macro's body, opened for walking.
///
/// Dropping it takes the macro's name back off the expansion stack, so a
/// second, sibling call to the same macro still expands while a cycle stops.
struct OpenMacro<'a> {
    name: String,
    content: Arc<str>,
    uri: Url,
    path: PathBuf,
    /// Byte offset of the closure within `content`.
    offset: u32,
    scope: &'a MacroScope,
}

impl Drop for OpenMacro<'_> {
    fn drop(&mut self) {
        self.scope.expanding.borrow_mut().remove(&self.name);
    }
}

/// Resolve a call to `method` against the project's router macros and open the
/// file holding the macro's body.
///
/// Returns `None` when no router macro of that name is registered, when its
/// file cannot be read, or when the macro is already being expanded further up
/// the call stack.
fn open_route_macro<'a>(scope: &'a MacroScope, method: &[u8]) -> Option<OpenMacro<'a>> {
    if scope.bodies.is_empty() {
        return None;
    }
    let name = std::str::from_utf8(method).ok()?.to_ascii_lowercase();
    let (uri, offset) = scope.bodies.get(&name)?;
    let url = Url::parse(uri).ok()?;
    let path = url.to_file_path().ok()?;
    if !scope.expanding.borrow_mut().insert(name.clone()) {
        return None;
    }
    // Constructed before the read so a failed read still pops the name off the
    // expansion stack when `open` is dropped.
    let mut open = OpenMacro {
        name,
        content: Arc::from(""),
        uri: url,
        path,
        offset: *offset,
        scope,
    };
    open.content = scope.source(uri)?;
    Some(open)
}

/// A macro body: the closure a `macro()` registration was given, or the one a
/// mixin method returns.
enum MacroBody<'ast, 'arena> {
    Closure(&'ast Closure<'arena>),
    Arrow(&'ast ArrowFunction<'arena>),
}

/// Find the closure a macro registration points at, by its byte offset.
fn macro_body_at<'ast, 'arena>(
    node: Node<'ast, 'arena>,
    offset: u32,
) -> Option<MacroBody<'ast, 'arena>> {
    match node {
        Node::Closure(closure) if closure.span().start.offset == offset => {
            return Some(MacroBody::Closure(closure));
        }
        Node::ArrowFunction(arrow) if arrow.span().start.offset == offset => {
            return Some(MacroBody::Arrow(arrow));
        }
        _ => {}
    }
    let mut found = None;
    node.visit_children(|child| {
        if found.is_none() {
            found = macro_body_at(child, offset);
        }
    });
    found
}

/// A file that a route source pulls in, opened for scanning.
///
/// Removing the path from the include stack again is what
/// [`IncludedFile::drop`] is for, so a diamond include (two groups pulling
/// in the same helper file) still scans both times while a true cycle stops.
struct IncludedFile<'a> {
    path: PathBuf,
    content: String,
    open: &'a RefCell<HashSet<PathBuf>>,
}

impl Drop for IncludedFile<'_> {
    fn drop(&mut self) {
        self.open.borrow_mut().remove(&self.path);
    }
}

/// Resolve an include target (`require __DIR__ . '/x.php'`,
/// `Route::group([], base_path('routes/x.php'))`) and read the file it
/// names, or return `None` when the path is not statically recoverable, the
/// file cannot be read, or following it would re-enter a file already open.
fn open_included_file<'a>(
    target: &Expression<'_>,
    content: &str,
    paths: ScanPaths<'a>,
) -> Option<IncludedFile<'a>> {
    let dir = paths.dir?;
    let path = resolve_path_arg(
        target,
        content,
        dir,
        paths.root.unwrap_or(dir),
        paths.program,
    )?;
    let path = path.canonicalize().unwrap_or(path);
    if !paths.open.borrow_mut().insert(path.clone()) {
        return None;
    }
    // Constructed before the read so that a failed read still pops the path
    // off the include stack when `included` is dropped.
    let mut included = IncludedFile {
        content: String::new(),
        path,
        open: paths.open,
    };
    included.content = std::fs::read_to_string(&included.path).ok()?;
    Some(included)
}

/// Invoke `f` on every statement nested inside `stmt` that a route
/// registration can appear in.
///
/// Route sources are ordinary PHP: registrations sit inside `if` blocks and
/// loops, and a service provider registers them from a method body.
/// Closures are deliberately not descended into here — a closure registers
/// routes only as a `->group()` body, and that path applies the group's name
/// and URI prefixes before walking it.  A `foreach` is likewise absent: its
/// body is walked once per element with the loop variables bound, which the
/// callers do themselves.
pub(super) fn for_each_nested_statement(stmt: &Statement<'_>, f: &mut dyn FnMut(&Statement<'_>)) {
    let mut visit = |statements: &[Statement<'_>]| statements.iter().for_each(&mut *f);

    match stmt {
        Statement::Namespace(ns) => visit(ns.statements().as_slice()),
        Statement::Block(b) => visit(b.statements.as_slice()),
        Statement::If(if_stmt) => crate::parser::for_each_if_branch(if_stmt, visit),
        Statement::While(w) => visit(w.body.statements()),
        Statement::DoWhile(dw) => f(dw.statement),
        Statement::For(fs) => visit(fs.body.statements()),
        Statement::Try(t) => {
            visit(t.block.statements.as_slice());
            for catch in t.catch_clauses.iter() {
                visit(catch.block.statements.as_slice());
            }
            if let Some(finally) = &t.finally_clause {
                visit(finally.block.statements.as_slice());
            }
        }
        Statement::Switch(sw) => {
            for case in sw.body.cases().iter() {
                match case {
                    SwitchCase::Expression(c) => visit(c.statements.as_slice()),
                    SwitchCase::Default(c) => visit(c.statements.as_slice()),
                }
            }
        }
        Statement::Function(func) => visit(func.body.statements.as_slice()),
        // A service provider is a route source in its own right: its
        // `map()`/`boot()` bodies are where `Route::group(…)` runs.
        Statement::Class(c) => visit_class_member_bodies(c.members.as_slice(), &mut visit),
        Statement::Trait(t) => visit_class_member_bodies(t.members.as_slice(), &mut visit),
        Statement::Enum(e) => visit_class_member_bodies(e.members.as_slice(), &mut visit),
        _ => {}
    }
}

fn visit_class_member_bodies(
    members: &[ClassLikeMember<'_>],
    visit: &mut impl FnMut(&[Statement<'_>]),
) {
    for member in members {
        if let ClassLikeMember::Method(method) = member
            && let MethodBody::Concrete(body) = &method.body
        {
            visit(body.statements.as_slice());
        }
    }
}

/// The expression naming the file an `include`/`require` construct pulls in.
fn include_target<'arena>(construct: &Construct<'arena>) -> Option<&'arena Expression<'arena>> {
    match construct {
        Construct::Include(c) => Some(c.value),
        Construct::IncludeOnce(c) => Some(c.value),
        Construct::Require(c) => Some(c.value),
        Construct::RequireOnce(c) => Some(c.value),
        _ => None,
    }
}

/// Resolve `route('name')` to the `->name('name')` declaration in `routes/`.
///
/// Supports both explicit full-name declarations:
///   `Route::get('/create', ...)->name('admin.email.template.create')`
///
/// And group prefix notation:
///   `Route::name('admin.email.template.')->group(fn() { Route::get(...)->name('create'); })`
pub(crate) fn resolve_route_definitions(backend: &Backend, name: &str) -> Vec<Location> {
    let mut sink = RouteDefinitions {
        target: name,
        out: Vec::new(),
    };
    walk_project_routes(backend, &mut sink);
    let mut results = sink.out;
    results.extend(super::folio::resolve_folio_route_definition(backend, name));
    results
}

/// Find-references starting from the `->name()` argument that registers a
/// route: every `route()` call naming it, plus the registration itself when
/// `include_declaration` is set.
///
/// `None` when the cursor is not on a route registration, which only a
/// routes file (the project's or one a package loads) can hold.
pub(crate) fn find_route_registration_references(
    backend: &Backend,
    uri: &str,
    content: &str,
    position: tower_lsp::lsp_types::Position,
    include_declaration: bool,
) -> Option<Vec<Location>> {
    use crate::symbol_map::LaravelStringKind;

    let is_route_file = uri.contains("/routes/")
        || Url::parse(uri)
            .ok()
            .and_then(|u| u.to_file_path().ok())
            .is_some_and(|path| {
                backend
                    .laravel_provider_resources
                    .read()
                    .route_files
                    .contains(&path)
            });
    if !is_route_file {
        return None;
    }

    let offset = crate::text_position::position_to_offset(content, position) as usize;
    let names = route_names_registered_at(backend, uri, offset);
    if names.is_empty() {
        return None;
    }

    let keys: Vec<_> = names
        .iter()
        .map(
            |key| crate::reference_index::ReferenceIndexKey::LaravelString {
                kind: LaravelStringKind::Route,
                key: key.clone(),
            },
        )
        .collect();
    let snapshot = backend.user_file_symbol_maps_for_reference_keys(&keys);
    let mut locations: Vec<Location> = Vec::new();
    for name in &names {
        for location in super::find_laravel_string_key_references(
            backend,
            &LaravelStringKind::Route,
            name,
            uri,
            &snapshot,
            include_declaration,
        ) {
            if !locations.contains(&location) {
                locations.push(location);
            }
        }
    }
    (!locations.is_empty()).then_some(locations)
}

/// The names of the routes whose `->name()` argument in `uri` covers byte
/// `offset`.
///
/// Every route file is walked rather than just `uri`, so a file included
/// under a named group still reports the group's prefix. A file that is
/// both walked on its own and included under a group reports both names.
fn route_names_registered_at(backend: &Backend, uri: &str, offset: usize) -> Vec<String> {
    let mut sink = RoutesRegisteredAt {
        uri,
        offset,
        out: Vec::new(),
    };
    walk_project_routes(backend, &mut sink);
    sink.out
}

/// Walk every route file of the project, then of its installed packages,
/// into `sink`.
fn walk_project_routes(backend: &Backend, sink: &mut dyn RouteSink) {
    let mut scanned: HashSet<PathBuf> = HashSet::new();
    let snapshot = backend.user_file_symbol_maps();
    let workspace_root = backend.workspace.workspace_root.read().clone();
    let macros = MacroScope::for_backend(backend);

    for (file_uri, _) in snapshot {
        if !file_uri.contains("/routes/") {
            continue;
        }
        let Ok(uri) = Url::parse(&file_uri) else {
            continue;
        };
        let Some(content) = backend.get_file_content(&file_uri) else {
            continue;
        };
        let path = uri.to_file_path().ok();
        if let Some(path) = path.clone() {
            scanned.insert(path.canonicalize().unwrap_or(path));
        }
        walk_route_file(
            &content,
            &uri,
            path.as_deref(),
            workspace_root.as_deref(),
            &macros,
            sink,
        );
    }

    for route_path in &backend.laravel_provider_resources.read().route_files {
        let canonical = route_path
            .canonicalize()
            .unwrap_or_else(|_| route_path.clone());
        if !scanned.insert(canonical) {
            continue;
        }
        if let Ok(content) = std::fs::read_to_string(route_path)
            && let Ok(uri) = Url::from_file_path(route_path)
        {
            walk_route_file(
                &content,
                &uri,
                Some(route_path),
                workspace_root.as_deref(),
                &macros,
                sink,
            );
        }
    }
}

/// Where go-to-definition lands for a route-name argument: between the quotes
/// of a plain literal, and at the start of anything else — an interpolated or
/// concatenated name has no single literal to point at.
fn name_offset(expr: &Expression<'_>, content: &str) -> usize {
    match extract_string_literal(expr, content) {
        Some((_, start, _)) => start,
        None => expr.span().start.offset as usize,
    }
}

/// A named route recovered from the project's route files.
#[derive(Debug)]
pub(crate) struct RouteEntry {
    /// Fully-qualified route name, with group name prefixes applied
    /// (e.g. `admin.users.index`).
    pub name: String,
    /// The URI the route was registered with, with group URI prefixes
    /// applied and reported the way Laravel's `Route::uri()` does: no
    /// leading slash, and `/` for the root route (e.g. `users/{user}`).
    ///
    /// Empty when the URI is not statically recoverable — a variable URI,
    /// or a name generated by `Route::resource()` rather than written out.
    pub uri: String,
    /// Whether the route was registered by an installed package rather
    /// than by the project itself.  A project that registers no routes of
    /// its own still sees every vendor package's routes, so consumers that
    /// need to know "does this project have a route table at all?" have to
    /// look past them.
    pub from_vendor: bool,
}

/// The result of scanning the project's route files.
#[derive(Debug)]
pub(crate) struct RouteDiscovery {
    /// Every named route that was statically resolved.
    pub routes: Vec<RouteEntry>,
    /// The name of every route in `routes`, sorted, shared so that a
    /// diagnostic pass or a completion reads the list rather than copying
    /// it.
    pub names: std::sync::Arc<[String]>,
    /// Name prefixes of groups whose `->name()` argument was not a string
    /// literal (e.g. `Route::name($panelId . '.')` inside Filament).  Routes
    /// starting with one of these prefixes cannot be judged: the full set of
    /// names under the prefix is unknowable through static analysis.
    pub open_prefixes: Vec<String>,
    /// Route names registered under a group whose name could not be
    /// statically recovered, recorded whole rather than as a prefix (e.g. a
    /// bare `Route::name($panelId)->group(…)` with no enclosing literal group
    /// spells out no known leading text at all, so no prefix can be
    /// recorded).  A `route()` call that *ends* with one of these cannot be
    /// judged: the unknown run of characters the group's name contributes
    /// could be anything, so only the part written out after it is known.
    pub open_suffixes: Vec<String>,
}

/// The name and URI prefixes a route inherits from the groups enclosing it,
/// and the receivers the router is reachable through at that point.
#[derive(Clone, Copy)]
struct GroupPrefix<'a> {
    /// Accumulated route-name prefix (`->name('admin.')`, `['as' => …]`).
    name: &'a str,
    /// Accumulated URI prefix (`->prefix('admin')`, `['prefix' => …]`).
    uri: &'a str,
    /// Whether this group or an enclosing one has a name that could not be
    /// statically recovered.  Once set, every route name registered beneath
    /// it is also recorded in [`RouteDiscovery::open_suffixes`], since the
    /// literal name alone (missing whatever the unknown group name
    /// contributes ahead of it) is not a route that necessarily exists.
    unknowable: bool,
    /// The variable (without its `$`) holding the router: `router` in a
    /// routes file, which Laravel's `RouteFileRegistrar` requires with
    /// `$router` in scope, and the first parameter of a group closure, which
    /// `Router::group()` calls with the router.
    router_var: Option<&'a str>,
    /// Whether `$this` is the router, as it is inside a router macro body.
    this_is_router: bool,
}

impl GroupPrefix<'_> {
    /// The scope a route source starts in, before any group opens.
    fn top_level() -> Self {
        GroupPrefix {
            name: "",
            uri: "",
            unknowable: false,
            router_var: Some("router"),
            this_is_router: false,
        }
    }

    /// Whether the call chain `expr` starts at the router, so that a
    /// `->name()` or registration verb along it is a route rather than some
    /// other builder's method (`$query->name('x')->get()`).
    ///
    /// The root has to be the `Route` facade, the router variable in scope,
    /// or `$this` inside a router macro.
    fn chain_reaches_router(&self, mut expr: &Expression<'_>, content: &str) -> bool {
        loop {
            match expr {
                Expression::Call(Call::Method(mc)) => expr = mc.object,
                Expression::Parenthesized(p) => expr = p.expression,
                Expression::Call(Call::StaticMethod(sc)) => {
                    return is_facade(sc.class, content, "Route");
                }
                Expression::Variable(Variable::Direct(variable)) => {
                    let name = bytes_to_str(variable.name).trim_start_matches('$');
                    return (self.this_is_router && name == "this")
                        || self.router_var == Some(name);
                }
                _ => return false,
            }
        }
    }
}

/// Where a route-file walk reports what it finds.
///
/// One walk serves both consumers: enumeration keeps every route it is handed,
/// and go-to-definition keeps the site of the ones whose name matches what the
/// user clicked.
trait RouteSink {
    /// A named route, registered at `site`.
    fn route(&mut self, route: RouteEntry, site: RouteSite<'_>);

    /// The name prefix of a group whose own name is not statically known.
    fn open_prefix(&mut self, _prefix: String) {}

    /// A route name registered under such a group, recorded whole.
    fn open_suffix(&mut self, _name: String) {}
}

/// Where a route name was written: the file being walked and the offset the
/// declaration resolves to.
#[derive(Clone, Copy)]
struct RouteSite<'a> {
    uri: &'a Url,
    content: &'a str,
    offset: usize,
    /// The byte range of the `->name()` argument that spells the name, when
    /// the route has one. A name a registrar prefix or `Route::resource()`
    /// generates has no argument of its own to stand on.
    name_arg: Option<(usize, usize)>,
}

/// The enumeration sink: keeps every route, plus the prefixes and suffixes of
/// route names an unknowable group leaves unjudgeable.
struct RouteCollector<'a> {
    out: &'a mut Vec<RouteEntry>,
    open_prefixes: &'a mut Vec<String>,
    open_suffixes: &'a mut Vec<String>,
}

impl RouteSink for RouteCollector<'_> {
    fn route(&mut self, route: RouteEntry, _site: RouteSite<'_>) {
        self.out.push(route);
    }

    fn open_prefix(&mut self, prefix: String) {
        self.open_prefixes.push(prefix);
    }

    fn open_suffix(&mut self, name: String) {
        self.open_suffixes.push(name);
    }
}

/// The go-to-definition sink: keeps where the routes named `target` were
/// registered.  A registration that generates several matching names (a
/// `Route::resource()` reached by a pattern) is one declaration site, so
/// repeats of a location are dropped.
struct RouteDefinitions<'a> {
    target: &'a str,
    out: Vec<Location>,
}

/// The find-references sink: keeps the names of the routes whose `->name()`
/// argument in `uri` covers `offset`.
struct RoutesRegisteredAt<'a> {
    uri: &'a str,
    offset: usize,
    out: Vec<String>,
}

impl RouteSink for RoutesRegisteredAt<'_> {
    fn route(&mut self, route: RouteEntry, site: RouteSite<'_>) {
        if let Some((start, end)) = site.name_arg
            && (start..=end).contains(&self.offset)
            && site.uri.as_str() == self.uri
            && !self.out.contains(&route.name)
        {
            self.out.push(route.name);
        }
    }
}

impl RouteSink for RouteDefinitions<'_> {
    fn route(&mut self, route: RouteEntry, site: RouteSite<'_>) {
        if !route_name_matches(self.target, &route.name) {
            return;
        }
        let location = crate::definition::point_location(
            site.uri.clone(),
            offset_to_position(site.content, site.offset),
        );
        if !self.out.contains(&location) {
            self.out.push(location);
        }
    }
}

/// Registration methods whose first argument is the route URI.
const URI_FIRST_ARG_METHODS: &[&[u8]] = &[
    b"get",
    b"post",
    b"put",
    b"patch",
    b"delete",
    b"options",
    b"any",
    b"view",
    b"redirect",
    b"permanentredirect",
];

/// Recover the URI a route was registered with from its call chain.
///
/// The walk starts at the receiver of `->name()` and descends through the
/// chain links until it reaches the registration call, so modifiers between
/// the two are skipped:
/// `Route::middleware('auth')->get('/users/{user}', …)->name('users.show')`
/// records `/users/{user}`.  `Route::match(['get', 'post'], '/uri', …)` keeps
/// its URI in the second argument.
fn chain_uri(expr: &Expression<'_>, content: &str, scope: &Scope) -> Option<String> {
    let (method, args) = match expr {
        Expression::Call(Call::Method(mc)) => match &mc.method {
            ClassLikeMemberSelector::Identifier(ident) => (ident.value, &mc.argument_list),
            _ => return chain_uri(mc.object, content, scope),
        },
        Expression::Call(Call::StaticMethod(sc)) => match &sc.method {
            ClassLikeMemberSelector::Identifier(ident) => (ident.value, &sc.argument_list),
            _ => return None,
        },
        _ => return None,
    };

    let lower = method.to_ascii_lowercase();
    let uri_arg = if URI_FIRST_ARG_METHODS.contains(&lower.as_slice()) {
        args.arguments.iter().next()
    } else if lower == b"match" {
        args.arguments.iter().nth(1)
    } else {
        None
    };
    if let Some(arg) = uri_arg {
        return const_string(arg.value(), content, scope);
    }

    // Not a registration link — keep descending the chain.
    match expr {
        Expression::Call(Call::Method(mc)) => chain_uri(mc.object, content, scope),
        _ => None,
    }
}

/// Whether a router method registers a route (as opposed to modifying the
/// registrar or the route it returns).
fn is_registration_verb(method: &[u8]) -> bool {
    URI_FIRST_ARG_METHODS
        .iter()
        .chain([b"match".as_slice(), b"fallback".as_slice()].iter())
        .any(|verb| method.eq_ignore_ascii_case(verb))
}

/// The name a `->name()` leaf gives its route, and what is left of the chain
/// to walk once it has been read.
struct LeafRoute<'e, 'arena> {
    /// `None` when some part of the name is not a statically-known string.
    name: Option<String>,
    /// The part of the chain ahead of the registration, or the whole receiver
    /// when no registration was found.
    rest: Option<&'e Expression<'arena>>,
}

/// Read the full name of the route a `->name()` link belongs to.
///
/// `Route::name()` on a route *appends* to the name the registrar put in its
/// action, so `Route::name('admin.')->get(…)->name('dash')->name('board')` is
/// `admin.dashboard`.  The walk goes down the chain through every `->name()`
/// link and any other modifier until it reaches the registration verb; the
/// chain ahead of the verb supplies the registrar's name.  A chain with no
/// registration verb (a router macro such as `Route::inertia(…)`) keeps the
/// link's own name alone, as it always has.
fn leaf_route_name<'e, 'arena>(
    mc: &'e MethodCall<'arena>,
    content: &str,
    scope: &Scope,
) -> LeafRoute<'e, 'arena> {
    let own = mc
        .argument_list
        .arguments
        .iter()
        .next()
        .and_then(|arg| const_string(arg.value(), content, scope));
    // Name segments outermost-first, the one on `mc` included.
    let mut segments = vec![own.clone()];
    let mut cur: &'e Expression<'arena> = mc.object;
    loop {
        let (method, object) = match cur {
            Expression::Call(Call::Method(link)) => match &link.method {
                ClassLikeMemberSelector::Identifier(ident) => (ident.value, Some(link)),
                _ => {
                    cur = link.object;
                    continue;
                }
            },
            Expression::Call(Call::StaticMethod(sc)) => match &sc.method {
                ClassLikeMemberSelector::Identifier(ident) => (ident.value, None),
                _ => break,
            },
            _ => break,
        };
        if is_registration_verb(method) {
            let (registrar, rest) = match object {
                Some(link) => (chain_name_prefix(link.object, content), Some(link.object)),
                None => (String::new(), None),
            };
            let name = segments
                .iter()
                .rev()
                .try_fold(registrar, |mut name, segment| {
                    name.push_str(segment.as_deref()?);
                    Some(name)
                });
            return LeafRoute { name, rest };
        }
        let Some(link) = object else {
            break;
        };
        if method.eq_ignore_ascii_case(b"name") {
            segments.push(
                link.argument_list
                    .arguments
                    .iter()
                    .next()
                    .and_then(|arg| const_string(arg.value(), content, scope)),
            );
        }
        cur = link.object;
    }
    LeafRoute {
        name: own,
        rest: Some(mc.object),
    }
}

/// Build the recorded URI of a route from its group prefix and own URI.
fn route_uri(group_uri: &str, own_uri: Option<&str>) -> String {
    let Some(own_uri) = own_uri else {
        return String::new();
    };
    let joined = join_uri_segments(group_uri, own_uri);
    if joined.is_empty() {
        "/".to_string()
    } else {
        joined
    }
}

/// Extract the parameter names from a route URI pattern.
///
/// `users/{user}/posts/{post?}` yields `["user", "post"]`: the optional
/// marker and the scoped-binding field of `{post:slug}` are stripped, so the
/// result is exactly the keys `route()`'s parameters array accepts.
pub(crate) fn route_uri_parameters(uri: &str) -> Vec<&str> {
    let mut params = Vec::new();
    let mut rest = uri;
    while let Some(open) = rest.find('{') {
        rest = &rest[open + 1..];
        let Some(close) = rest.find('}') else {
            break;
        };
        let raw = &rest[..close];
        rest = &rest[close + 1..];
        let name = raw
            .split_once(':')
            .map_or(raw, |(name, _field)| name)
            .trim_end_matches('?');
        if !name.is_empty() {
            params.push(name);
        }
    }
    params
}

/// Collect all named routes defined in `routes/` files.
///
/// Returns a sorted, deduplicated list of fully-qualified route names with
/// the URI each was registered with.
///
/// Follows `Route::group([], __DIR__ . '/sub.php')` file includes so
/// that routes in sub-files inherit the parent group's prefixes.
pub(crate) fn enumerate_all_routes(backend: &Backend) -> RouteDiscovery {
    let mut routes = Vec::new();
    let mut open_prefixes = Vec::new();
    let mut open_suffixes = Vec::new();
    let mut scanned: HashSet<PathBuf> = HashSet::new();
    let snapshot = backend.user_file_symbol_maps();
    let workspace_root = backend.workspace.workspace_root.read().clone();
    let macros = MacroScope::for_backend(backend);

    for (file_uri, _) in snapshot {
        if !file_uri.contains("/routes/") {
            continue;
        }
        // Skip sub-directory route files at the top level — they are
        // included by parent files via `Route::group([], __DIR__ . '/sub.php')`
        // and should only be scanned in that context to inherit the
        // correct name prefix.  A "sub-directory" file is one where the
        // path after the last `/routes/` segment contains another `/`.
        if let Some(after) = file_uri.rsplit("/routes/").next()
            && after.contains('/')
        {
            continue;
        }
        let Some(content) = backend.get_file_content(&file_uri) else {
            continue;
        };
        let Ok(uri) = Url::parse(&file_uri) else {
            continue;
        };
        let path = uri.to_file_path().ok();
        if let Some(ref p) = path {
            scanned.insert(p.canonicalize().unwrap_or_else(|_| p.clone()));
        }
        let before = routes.len();
        walk_route_file(
            &content,
            &uri,
            path.as_deref(),
            workspace_root.as_deref(),
            &macros,
            &mut RouteCollector {
                out: &mut routes,
                open_prefixes: &mut open_prefixes,
                open_suffixes: &mut open_suffixes,
            },
        );
        if file_uri.contains("/vendor/") {
            mark_from_vendor(&mut routes[before..]);
        }
    }

    for route_path in &backend.laravel_provider_resources.read().route_files {
        let canonical = route_path
            .canonicalize()
            .unwrap_or_else(|_| route_path.clone());
        if !scanned.insert(canonical) {
            continue;
        }
        if let Ok(content) = std::fs::read_to_string(route_path)
            && let Ok(uri) = Url::from_file_path(route_path)
        {
            let before = routes.len();
            walk_route_file(
                &content,
                &uri,
                Some(route_path),
                workspace_root.as_deref(),
                &macros,
                &mut RouteCollector {
                    out: &mut routes,
                    open_prefixes: &mut open_prefixes,
                    open_suffixes: &mut open_suffixes,
                },
            );
            if route_path
                .components()
                .any(|part| part.as_os_str() == "vendor")
            {
                mark_from_vendor(&mut routes[before..]);
            }
        }
    }

    // Folio pages register no `Route::` call at all, so they are invisible
    // to everything above and are discovered by their own filesystem-based
    // scan instead.
    routes.extend(super::folio::enumerate_folio_routes(backend));

    // Sorting the project's own registrations ahead of a package's, and
    // known URIs ahead of unknown ones, then deduping to one entry per
    // name, means a name registered both with a literal URI and by
    // `Route::resource()` keeps the URI it has.
    routes.sort_by(|a, b| {
        a.name
            .cmp(&b.name)
            .then_with(|| a.from_vendor.cmp(&b.from_vendor))
            .then_with(|| a.uri.is_empty().cmp(&b.uri.is_empty()))
            .then_with(|| a.uri.cmp(&b.uri))
    });
    routes.dedup_by(|a, b| a.name == b.name);
    open_prefixes.sort();
    open_prefixes.dedup();
    open_suffixes.sort();
    open_suffixes.dedup();
    // `routes` is sorted by name and deduplicated, so the names come out
    // sorted too.
    let names: std::sync::Arc<[String]> = routes.iter().map(|route| route.name.clone()).collect();
    RouteDiscovery {
        routes,
        names,
        open_prefixes,
        open_suffixes,
    }
}

fn mark_from_vendor(routes: &mut [RouteEntry]) {
    for route in routes {
        route.from_vendor = true;
    }
}

/// Parse a single route file and walk every `->name('...')` value into `sink`,
/// accounting for group prefixes and file includes.
fn walk_route_file(
    content: &str,
    uri: &Url,
    file_path: Option<&Path>,
    workspace_root: Option<&Path>,
    macros: &MacroScope,
    sink: &mut dyn RouteSink,
) {
    let open = RefCell::new(HashSet::new());
    if let Some(path) = file_path {
        open.borrow_mut()
            .insert(path.canonicalize().unwrap_or_else(|_| path.to_path_buf()));
    }
    in_parsed_route_file(content, b"input.php", |program| {
        let paths = ScanPaths::new(
            file_path.and_then(Path::parent),
            workspace_root,
            &open,
            macros,
            program,
            uri,
        );

        let mut scope = Scope::default();
        for stmt in program.statements.iter() {
            walk_stmt(
                stmt,
                content,
                GroupPrefix::top_level(),
                paths,
                &mut scope,
                sink,
            );
        }
    });
}

fn walk_stmt(
    stmt: &Statement<'_>,
    content: &str,
    group: GroupPrefix<'_>,
    paths: ScanPaths<'_>,
    scope: &mut Scope,
    sink: &mut dyn RouteSink,
) {
    match stmt {
        Statement::Expression(e) => {
            walk_expr(e.expression, content, group, paths, scope, sink);
        }
        Statement::Return(r) => {
            if let Some(v) = r.value {
                walk_expr(v, content, group, paths, scope, sink);
            }
        }
        // A loop over a literal array registers one route per element, so the
        // body is walked once per element with the loop variables bound to it.
        Statement::Foreach(fe) => {
            for_each_iteration(fe, content, scope, &mut |scope| {
                for nested in fe.body.statements() {
                    walk_stmt(nested, content, group, paths, scope, sink);
                }
            });
            return;
        }
        _ => {}
    }
    for_each_nested_statement(stmt, &mut |nested| {
        walk_stmt(nested, content, group, paths, scope, sink);
    });
}

fn walk_expr(
    expr: &Expression<'_>,
    content: &str,
    group: GroupPrefix<'_>,
    paths: ScanPaths<'_>,
    scope: &mut Scope,
    sink: &mut dyn RouteSink,
) {
    // A chain that registers a resource generates its whole route set here;
    // none of the per-route handling below applies to it.
    if let Some(registration) = resource_registration(expr, content)
        && group.chain_reaches_router(expr, content)
    {
        push_resource_routes(
            &registration,
            group,
            RouteSite {
                uri: paths.uri,
                content,
                offset: registration.name_offset,
                name_arg: None,
            },
            sink,
        );
        // A `->group()` sharing the chain registers routes of its own, which
        // the resource shortcut must not swallow.
        if let Some(preceding) = registration.preceding {
            walk_expr(preceding, content, group, paths, scope, sink);
        }
        return;
    }

    match expr {
        Expression::Call(Call::Method(mc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &mc.method else {
                walk_expr(mc.object, content, group, paths, scope, sink);
                return;
            };
            let method = ident.value.to_ascii_lowercase();

            if method == b"group" {
                // When the chain includes a `->name()` whose argument is not
                // a string literal, the accumulated prefix is incomplete and
                // routes under it cannot be judged.  Whatever known text was
                // written out is still recorded as an open prefix, and every
                // route name registered inside the group from here on is
                // also unknowable, regardless of whether that text is empty.
                let dynamic_head = chain_dynamic_name_prefix(mc.object, content, scope);
                if let Some(head) = &dynamic_head {
                    record_open_prefix(group.name, head, sink);
                }
                let name_prefix =
                    format!("{}{}", group.name, chain_name_prefix(mc.object, content));
                let uri_prefix =
                    join_uri_segments(group.uri, &chain_uri_prefix(mc.object, content));
                let inner = GroupPrefix {
                    name: &name_prefix,
                    uri: &uri_prefix,
                    unknowable: group.unknowable || dynamic_head.is_some(),
                    ..group
                };
                for arg in mc.argument_list.arguments.iter() {
                    walk_group_body(arg.value(), content, inner, paths, scope, sink);
                }
            } else if method == b"name" {
                let leaf = leaf_route_name(mc, content, scope);
                if let Some(first_arg) = mc.argument_list.arguments.iter().next()
                    && let Some(name_val) = &leaf.name
                    && group.chain_reaches_router(mc.object, content)
                {
                    let full = format!("{}{name_val}", group.name);
                    // Only collect leaf names (non-prefix names that don't end with '.').
                    if !full.is_empty() && !full.ends_with('.') {
                        // A group ancestor left its own name unknowable, so
                        // this route's real name has an unrecoverable run of
                        // characters ahead of `full` — record it as an open
                        // suffix rather than trusting `full` as the whole
                        // name.
                        if group.unknowable {
                            sink.open_suffix(full.clone());
                        }
                        // A `->prefix()` on the route's own chain
                        // (`Route::prefix('admin')->get(…)`) prefixes the URI
                        // just as an enclosing group's does.
                        let uri_prefix =
                            join_uri_segments(group.uri, &chain_uri_prefix(mc.object, content));
                        sink.route(
                            RouteEntry {
                                name: full,
                                uri: route_uri(
                                    &uri_prefix,
                                    chain_uri(mc.object, content, scope).as_deref(),
                                ),
                                from_vendor: false,
                            },
                            RouteSite {
                                uri: paths.uri,
                                content,
                                offset: name_offset(first_arg.value(), content),
                                name_arg: {
                                    let span = first_arg.value().span();
                                    Some((span.start.offset as usize, span.end.offset as usize))
                                },
                            },
                        );
                    }
                }
                if let Some(rest) = leaf.rest {
                    walk_expr(rest, content, group, paths, scope, sink);
                }
            } else if is_registration_verb(ident.value) {
                // `Route::name('users.index')->get(…)`: the registrar's name
                // becomes the route's even with no `->name()` after the verb.
                let registrar = chain_name_prefix(mc.object, content);
                let full = format!("{}{registrar}", group.name);
                if !registrar.is_empty()
                    && !full.ends_with('.')
                    && group.chain_reaches_router(mc.object, content)
                {
                    if group.unknowable {
                        sink.open_suffix(full.clone());
                    }
                    let uri_prefix =
                        join_uri_segments(group.uri, &chain_uri_prefix(mc.object, content));
                    sink.route(
                        RouteEntry {
                            name: full,
                            uri: route_uri(&uri_prefix, chain_uri(expr, content, scope).as_deref()),
                            from_vendor: false,
                        },
                        RouteSite {
                            uri: paths.uri,
                            content,
                            offset: expr.span().start.offset as usize,
                            name_arg: None,
                        },
                    );
                }
                walk_expr(mc.object, content, group, paths, scope, sink);
            } else if !walk_macro(ident.value, Some(mc.object), content, group, paths, sink) {
                walk_expr(mc.object, content, group, paths, scope, sink);
            }
        }
        Expression::Call(Call::StaticMethod(sc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &sc.method else {
                return;
            };
            let method_lower = ident.value.to_ascii_lowercase();

            if method_lower == b"group" {
                let args = || sc.argument_list.arguments.iter().map(|a| a.value());
                // `['as' => $dynamic]` is the legacy spelling of the fluent
                // `->name($dynamic)` group above and leaves the same names
                // unknowable.
                let dynamic_head = dynamic_as_prefix_from_args(args(), content, scope);
                if let Some(head) = &dynamic_head {
                    record_open_prefix(group.name, head, sink);
                }
                let name_prefix = format!(
                    "{}{}",
                    group.name,
                    extract_as_prefix_from_args(args(), content)
                );
                let uri_prefix =
                    join_uri_segments(group.uri, &extract_uri_prefix_from_args(args(), content));
                let inner = GroupPrefix {
                    name: &name_prefix,
                    uri: &uri_prefix,
                    unknowable: group.unknowable || dynamic_head.is_some(),
                    ..group
                };
                for arg in sc.argument_list.arguments.iter() {
                    walk_group_body(arg.value(), content, inner, paths, scope, sink);
                }
            } else {
                // `Auth::routes()` registers nothing itself: the facade
                // forwards to the router's `auth` macro, which `laravel/ui`
                // ships as a mixin.
                let macro_name: &[u8] =
                    if method_lower == b"routes" && is_facade(sc.class, content, "Auth") {
                        b"auth"
                    } else {
                        ident.value
                    };
                walk_macro(macro_name, None, content, group, paths, sink);
            }
        }
        // The data a route file loops over is usually built in a variable
        // first, and a registration is occasionally assigned to one too.
        Expression::Assignment(assignment) => {
            bind_assignment(assignment, content, scope);
            walk_expr(assignment.rhs, content, group, paths, scope, sink);
        }
        // A route file pulled in by `require`/`include` registers its routes
        // under whichever group encloses the include.
        Expression::Construct(construct) => {
            if let Some(file) = include_target(construct) {
                walk_included_file(file, content, group, paths, scope, sink);
            }
        }
        _ => {}
    }
}

/// Record the prefix a group whose own name is not statically known leaves
/// open: what its enclosing groups contribute, plus however much of its own
/// name was written out.
///
/// A group that leaves nothing at all known (`Route::name($prefix)` at the top
/// of a routes file) is not recorded: the empty prefix is a prefix of every
/// route name there is, so it would stop route names being judged anywhere in
/// the project rather than under the one group.
fn record_open_prefix(group_name: &str, head: &str, sink: &mut dyn RouteSink) {
    let prefix = format!("{group_name}{head}");
    if !prefix.is_empty() {
        sink.open_prefix(prefix);
    }
}

/// Whether the subject of a static call spells the Laravel facade `facade`
/// (`Auth`, `Route`), by its short name or its full one.
fn is_facade(class: &Expression<'_>, content: &str, facade: &str) -> bool {
    let span = class.span();
    let Some(text) = content.get(span.start.offset as usize..span.end.offset as usize) else {
        return false;
    };
    let text = text.trim_start_matches('\\');
    let short = text
        .strip_prefix("Illuminate\\Support\\Facades\\")
        .unwrap_or(text);
    short.eq_ignore_ascii_case(facade)
}

/// Collect the route names a call to the router macro `method` registers.
///
/// A macro body registers on the router itself (`$this->get(…)->name(…)`), so
/// it is walked exactly as a `->group()` closure is, with the prefixes in force
/// at the call site — both the enclosing groups' and any the chain ahead of the
/// call adds, since `Route::name('admin.')->auth()` prefixes the macro's routes
/// the way it would a group's.
///
/// Returns `false` when `method` names no known router macro, so a caller
/// looking at an ordinary chain link can carry on down the chain.
fn walk_macro(
    method: &[u8],
    chain: Option<&Expression<'_>>,
    content: &str,
    group: GroupPrefix<'_>,
    paths: ScanPaths<'_>,
    sink: &mut dyn RouteSink,
) -> bool {
    let Some(open) = open_route_macro(paths.macros, method) else {
        return false;
    };
    let name_prefix = match chain {
        Some(chain) => format!("{}{}", group.name, chain_name_prefix(chain, content)),
        None => group.name.to_string(),
    };
    let uri_prefix = match chain {
        Some(chain) => join_uri_segments(group.uri, &chain_uri_prefix(chain, content)),
        None => group.uri.to_string(),
    };
    let inner = GroupPrefix {
        name: &name_prefix,
        uri: &uri_prefix,
        unknowable: group.unknowable,
        // The macro closure is bound to the router and sees none of the
        // caller's variables.
        router_var: None,
        this_is_router: true,
    };
    in_parsed_route_file(&open.content, b"macro.php", |program| {
        let sub_paths = ScanPaths {
            dir: open.path.parent(),
            program,
            uri: &open.uri,
            ..paths
        };

        // A macro closure is registered without a `use (...)` clause, so it
        // has no access to the caller's local variables; its body gets its own
        // scope.
        let mut scope = Scope::default();
        match macro_body_at(Node::Program(program), open.offset) {
            Some(MacroBody::Closure(closure)) => {
                for stmt in closure.body.statements.iter() {
                    walk_stmt(stmt, &open.content, inner, sub_paths, &mut scope, sink);
                }
            }
            Some(MacroBody::Arrow(arrow)) => {
                walk_expr(
                    arrow.expression,
                    &open.content,
                    inner,
                    sub_paths,
                    &mut scope,
                    sink,
                );
            }
            None => {}
        }
    });
    true
}

/// Record the conventional routes a `Route::resource()` registration
/// generates, deriving each URI from the resource name the way Laravel's
/// `ResourceRegistrar` does.
fn push_resource_routes(
    registration: &ResourceRegistration<'_>,
    group: GroupPrefix<'_>,
    site: RouteSite<'_>,
    sink: &mut dyn RouteSink,
) {
    let (path_prefix, resource) = split_resource_prefix(registration.name);
    let segments: Vec<&str> = resource.split('.').filter(|s| !s.is_empty()).collect();
    let Some(last) = segments.last().copied() else {
        return;
    };

    // Every URI prefix in scope — the enclosing groups' and the one a slash in
    // the resource name implies — is applied once here rather than per
    // generated route.  A `->prefix()` on the registration's own chain is not
    // among them: `ResourceRegistrar` never reads it.
    let uri_prefix = join_uri_segments(group.uri, path_prefix);
    let collection_name = segments.join(".");
    let collection_uri = join_uri_segments(
        &uri_prefix,
        &nested_resource_uri(&segments, &registration.parameters),
    );
    // `->shallow()` reduces a nested resource to its last segment on the
    // routes that already identify the child by its own id — the name loses
    // the parent segments along with the URI.
    let shallow_uri = registration
        .shallow
        .then(|| join_uri_segments(&uri_prefix, last));
    let (member_uri, member_name): (&str, &str) = match shallow_uri.as_deref() {
        Some(uri) => (uri, last),
        None => (&collection_uri, &collection_name),
    };
    let wildcard = resource_wildcard(last, &registration.parameters);

    let suffixes = filtered_resource_suffixes(
        registration.is_api,
        registration.only.as_deref(),
        registration.except.as_deref(),
    );
    for suffix in suffixes {
        let (name_base, uri) = match suffix {
            "create" => (collection_name.as_str(), format!("{collection_uri}/create")),
            "show" | "update" | "destroy" => (member_name, format!("{member_uri}/{{{wildcard}}}")),
            "edit" => (member_name, format!("{member_uri}/{{{wildcard}}}/edit")),
            // index and store.
            _ => (collection_name.as_str(), collection_uri.clone()),
        };
        let name = resource_route_name(registration, name_base, suffix, group.name);
        // As with a plain `->name()` leaf, an ancestor group whose own name
        // is unknowable means `name` is missing whatever unrecoverable text
        // that group contributes ahead of it.
        if group.unknowable {
            sink.open_suffix(name.clone());
        }
        sink.route(
            RouteEntry {
                name,
                uri,
                from_vendor: false,
            },
            site,
        );
    }
}

/// The name Laravel gives one generated resource route.
///
/// Mirrors `ResourceRegistrar::getResourceRouteName()`: a per-method
/// `->names([…])` / `->name($method, …)` entry is the whole name and skips the
/// `->as()` prefix, `->names('images')` replaces the resource name but keeps
/// it, and the trailing `trim` is what keeps a resource registered under an
/// empty name from producing a leading dot.  The enclosing groups' name
/// prefix is applied outside that, so it reaches even the per-method form.
fn resource_route_name(
    registration: &ResourceRegistration<'_>,
    name_base: &str,
    suffix: &str,
    group_name: &str,
) -> String {
    if let Some((_, route_name)) = registration
        .names_by_method
        .iter()
        .rev()
        .find(|(method, _)| method == suffix)
    {
        return format!("{group_name}{route_name}");
    }
    let base = registration.names_all.as_deref().unwrap_or(name_base);
    let prefix = match registration.name_prefix.as_deref() {
        Some(prefix) => format!("{prefix}."),
        None => String::new(),
    };
    let name = format!("{prefix}{base}.{suffix}");
    format!("{group_name}{}", name.trim_matches('.'))
}

/// Walk the argument that was passed to `->group()`.
///
/// Handles closures, arrow functions, and the file-path form
/// (`Route::group([], __DIR__ . '/sub.php')`), so routes defined in an
/// included sub-file are reached too.
fn walk_group_body(
    expr: &Expression<'_>,
    content: &str,
    group: GroupPrefix<'_>,
    paths: ScanPaths<'_>,
    scope: &mut Scope,
    sink: &mut dyn RouteSink,
) {
    match expr {
        Expression::Closure(closure) => {
            let group = match closure.parameter_list.parameters.first() {
                Some(param) => GroupPrefix {
                    router_var: Some(bytes_to_str(param.variable.name).trim_start_matches('$')),
                    ..group
                },
                None => group,
            };
            for stmt in closure.body.statements.iter() {
                walk_stmt(stmt, content, group, paths, scope, sink);
            }
        }
        Expression::ArrowFunction(af) => {
            walk_expr(af.expression, content, group, paths, scope, sink);
        }
        // `Route::group([], __DIR__ . '/sub.php')` names a file rather than a
        // callback.
        _ => walk_included_file(expr, content, group, paths, scope, sink),
    }
}

/// Walk a file another route source pulls in.
///
/// The file is walked with the group prefix in force at the include site so
/// its routes inherit the enclosing group's name (e.g. `admin.`).  Walking
/// with an empty prefix would produce unprefixed names that are incorrect,
/// which is why `walk_route_file` (which resets the prefix) is not used here.
fn walk_included_file(
    file: &Expression<'_>,
    content: &str,
    group: GroupPrefix<'_>,
    paths: ScanPaths<'_>,
    scope: &mut Scope,
    sink: &mut dyn RouteSink,
) {
    let Some(included) = open_included_file(file, content, paths) else {
        return;
    };
    let sub_uri = Url::from_file_path(&included.path).unwrap_or_else(|_| paths.uri.clone());

    in_parsed_route_file(&included.content, b"included.php", |program| {
        let sub_paths = ScanPaths {
            dir: included.path.parent(),
            program,
            uri: &sub_uri,
            ..paths
        };

        for stmt in program.statements.iter() {
            walk_stmt(stmt, &included.content, group, sub_paths, scope, sink);
        }
    });
}

use super::helpers::{chain_uri_prefix, extract_uri_prefix_from_args, join_uri_segments};

pub(crate) use super::helpers::{chain_name_prefix, extract_as_prefix_from_args};

#[cfg(test)]
#[path = "route_names_tests.rs"]
mod tests;
